// TODO These code bits don't really belong here, but this is the only
// shared bit of js

function tabulate(list) {
  var result = '';
  $.each(list, function (index) {
    if (this.length == 2) {
      if (this[1].length)
        result += "   " + this[0] + ": " + this[1] + "\n";
    } else {
      result += "   " + this + "\n";
    }
  });
  return result;
}


String.prototype.escapeHtml = function () {
  return this.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}


function template(tmpl, data) {
  var brag = tmpl.replace(/\$([_A-Za-z.]+)/g, function (str, p1) {
    var dict = data;
    $.each(p1.split("."), function (i,v) {
      if (!dict) return true;
      if (v == "___") {
        dict = tabulate(dict);
      } else {
        dict = dict[v.replace("_"," ")];
        if (typeof dict == typeof "")
          dict = dict.escapeHtml();
      }
      return null;
    });
    if (dict === undefined) dict = '';
    return dict;
  });
  return brag;
}

// Original work copyright © 2010 Johannes Baagøe, under MIT license
// This is a derivative work copyright (c) 2017-2020, W. Mac" McMeans, under BSD license.
/* private: dependent string hash function */
function Mash() {
    var n = 4022871197; // 0xefc8249d

    var mash = function( data ) {
        data = data.toString();
        
        // cache the length
        for( var i = 0, l = data.length; i < l; i++ ) {
            n += data.charCodeAt( i );
            
            var h = 0.02519603282416938 * n;
            
            n  = h >>> 0;
            h -= n;
            h *= n;
            n  = h >>> 0;
            h -= n;
            n += h * 4294967296; // 0x100000000      2^32
        }
        return ( n >>> 0 ) * 2.3283064365386963e-10; // 2^-32
    };

    mash.version = 'Mash 0.9';
    return mash;
};


// From http://baagoe.com/en/RandomMusings/javascript/
function Alea() {
  return (function(args) {
    // Johannes BaagÃƒÂ¸e <baagoe@baagoe.com>, 2010
    var s0 = 0;
    var s1 = 0;
    var s2 = 0;
    var c = 1;

    if (!args.length) {
      args = [+new Date];
    }
    var mash = Mash();
    s0 = mash(' ');
    s1 = mash(' ');
    s2 = mash(' ');

    for (var i = 0; i < args.length; i++) {
      s0 -= mash(args[i]);
      if (s0 < 0) {
        s0 += 1;
      }
      s1 -= mash(args[i]);
      if (s1 < 0) {
        s1 += 1;
      }
      s2 -= mash(args[i]);
      if (s2 < 0) {
        s2 += 1;
      }
    }
    mash = null;

    var random = function() {
      var t = 2091639 * s0 + c * 2.3283064365386963e-10; // 2^-32
      s0 = s1;
      s1 = s2;
      return s2 = t - (c = t | 0);
    };
    random.uint32 = function() {
      return random() * 0x100000000; // 2^32
    };
    random.fract53 = function() {
      return random() +
        (random() * 0x200000 | 0) * 1.1102230246251565e-16; // 2^-53
    };
    random.version = 'Alea 0.9';
    random.args = args;
    random.state = function (newstate) {
      if (newstate) {
        s0 = newstate[0];
        s1 = newstate[1];
        s2 = newstate[2];
        c = newstate[3];
      }
      return [s0,s1,s2,c];
    };
    return random;

  } (Array.prototype.slice.call(arguments)));
}

var seed = new Alea();

function Random(n) {
  return seed.uint32() % n;
}

function randseed(set) {
  return seed.state(set);
}

function Pick(a) {
  return a[Random(a.length)];
}

var KParts = [
  'br|ch|cr|dr|fr|gr|h|j|kr|l|m|n|pr|r|sch|tr|v|wh|x|y|z'.split('|'),
  'a|a|e|e|i|i|o|o|u|u|ae|ie|oo|ou'.split('|'),
  'b|ck|d|g|k|m|n|p|t|v|x|z'.split('|')];

function GenerateName() {
  var result = '';
  for (var i = 0; i <= 5; ++i)
    result += Pick(KParts[i % 3]);
  return result.charAt(0).toUpperCase() + result.slice(1);
}

function LocalStorage() {
  this.getItem = function (key, callback) {
    var result = window.localStorage.getItem(key);
    if (callback)
      callback(result);
  };

  this.setItem = function (key, value, callback) {
    window.localStorage.setItem(key, value);
    if (callback)
      callback();
  };

  this.removeItem = function (key) {
    window.localStorage.removeItem(key);
  };
}


function CookieStorage() {
  this.getItem = function(key, callback) {
    var result;
    $.each(document.cookie.split(";"), function (i,cook) {
      if (cook.split("=")[0] === key)
        result = unescape(cook.split("=")[1]);
    });
    if (callback)
      setTimeout(function () { callback(result); }, 0);
    return result;
  };

  this.setItem = function (key, value, callback) {
    document.cookie = key + "=" + escape(value);
    if (callback)
      setTimeout(callback, 0);
  };

  this.removeItem = function (key) {
    document.cookie = key + "=; expires=Thu, 01-Jan-70 00:00:01 GMT;";
  };
}

function SqlStorage() {
  this.async = true;

  this.db = window.openDatabase("pqr", "", "Progress Quest Remix", 2500);

  this.db.transaction(function(tx) {
    tx.executeSql("CREATE TABLE IF NOT EXISTS Storage(key TEXT UNIQUE, value TEXT)");
  });

  this.getItem = function(key, callback) {
    this.db.transaction(function (tx) {
      tx.executeSql("SELECT value FROM Storage WHERE key=?", [key], function(tx, rs) {
        if (rs.rows.length)
          callback(rs.rows.item(0).value);
        else
          callback();
      });
    });
  };

  this.setItem = function (key, value, callback) {
    this.db.transaction(function (tx) {
      tx.executeSql("INSERT OR REPLACE INTO Storage (key,value) VALUES (?,?)",
                    [key, value],
                    callback);
    });
  };

  this.removeItem = function (key) {
    this.db.transaction(function (tx) {
      tx.executeSql("DELETE FROM Storage WHERE key=?", [key]);
    });
  };
}

function UrlEncode(s) {
  return encodeURIComponent(s).replace(/%20/g, "+");
}

var iPad = navigator.userAgent.match(/iPad/);
var iPod = navigator.userAgent.match(/iPod/);
var iPhone = navigator.userAgent.match(/iPhone/);
var iOS = iPad || iPod || iPhone;

function HasLocalStorage() {
  // Accessing window.localStorage can itself throw (e.g. blocked cookies).
  try {
    var k = '__pq_probe__';
    window.localStorage.setItem(k, k);
    window.localStorage.removeItem(k);
    return true;
  } catch (e) {
    return false;
  }
}

// localStorage everywhere it works. Older builds forced iOS onto WebSQL,
// which browsers are removing; rosters saved there are copied over once
// (see LocalStorage.getItem below).
var storage = (HasLocalStorage() ? new LocalStorage() :
               window.openDatabase ? new SqlStorage() :
               new CookieStorage());

if (storage instanceof LocalStorage && window.openDatabase) {
  (function (getItem) {
    storage.getItem = function (key, callback) {
      var value = window.localStorage.getItem(key);
      if (key !== 'roster' || value) return getItem.call(this, key, callback);
      // Nothing in localStorage yet: look for a legacy WebSQL roster.
      var done = false;
      function finish(legacy) {
        if (done) return;
        done = true;
        if (legacy) window.localStorage.setItem(key, legacy);
        if (callback) callback(legacy || value);
      }
      try {
        window.openDatabase("pqr", "", "Progress Quest Remix", 2500)
          .readTransaction(function (tx) {
            tx.executeSql("SELECT value FROM Storage WHERE key=?", [key],
              function (tx, rs) { finish(rs.rows.length ? rs.rows.item(0).value : null); },
              function () { finish(null); return false; });
          }, function () { finish(null); });
      } catch (e) {
        finish(null);
      }
    };
  })(storage.getItem);
}

storage.loadRoster = function (callback) {
  function gotItem(value) {
    if (value) {
      try {
        value = JSON.parse(value);
      } catch (err) {
        // aight
      }
    }
    value = value || {};
    callback(value);
    storage.games = value;
  }
  this.getItem("roster", gotItem);
}

storage.loadSheet = function (name, callback) {
  return this.loadRoster(function (games) {
    if (callback)
      callback(games[name]);
  });
}

storage.storeRoster = function (roster, callback) {
  this.games = roster;
  try {
    this.setItem("roster", JSON.stringify(roster), callback);
  } catch (err) {
    if (err.name === "QuotaExceededError" ||
        err.name === "NS_ERROR_DOM_QUOTA_REACHED" ||
        err.toString().indexOf("QUOTA_EXCEEDED_ERR") != -1) {
      alert("This browser lacks storage capacity to save this game. This game can continue but cannot be saved. (Mobile Safari, I'll wager?)");
      this.storeRoster = function (roster, callback) {
        setTimeout(callback, 0);
      };
      setTimeout(callback, 0);
    } else {
      throw err;
    }
  }
}

storage.addToRoster = function (newguy, callback) {
  this.loadRoster(function (games) {
    games[newguy.Traits.Name] = newguy;
    storage.storeRoster(games, callback);
  });
}

Number.prototype.div = function (divisor) {
  var dividend = this / divisor;
  return (dividend < 0 ? Math.ceil : Math.floor)(dividend);
};

function LevelUpTime(level) {  // seconds
  // Normally 20 minutes for level 1. Set to 3 for testing
  // exponential increase after that
  return Math.round((3 + Math.pow(1.15, level)) * 60);
}

let RevString = '&rev=6';
// Rev strings known to server, probably:
// rev=3 is the minimum allowed by server, probably pq6.1
// rev=4 is pq6.2 the longstanding delphi client
// rev=5 is pq6.3 presumably the lazarus port or other unofficial release
// rev=6 is this here, pq-web multiplayer enabled

// Character names travel in the URL hash (main.html#Name). New links use
// encodeURIComponent; old links and bookmarks used escape(), so decoding
// falls back to unescape() for those.
function EncodeName(name) {
  return encodeURIComponent(name);
}

function DecodeName(s) {
  s = s || '';
  try {
    return decodeURIComponent(s);
  } catch (e) {
    return unescape(s);
  }
}

// Save format version. Bump this and add an entry to SaveMigrations
// whenever a change needs existing saves to be patched.
var SaveVersion = 6;

// SaveMigrations[n] upgrades a save from version n to n+1. Saves made
// before versioning existed count as version 0.
var SaveMigrations = [
  // 0 -> 1: correctly spelled spells were showing up as new spells when
  // the misspelled one was already in the spell book.
  function (sheet) {
    function patch(from, to) {
      function count(spell) {
        var t = sheet.Spells.filter(function (a) { return a[0] == spell; });
        return t.length == 1 ? toArabic(t[0][1]) : 0;
      }
      var tf = count(from);
      if (!tf) return;
      var total = tf + count(to);
      sheet.Spells = sheet.Spells.filter(function (a) { return a[0] != to; });
      sheet.Spells.forEach(function (spell) {
        if (spell[0] == from) {
          spell[0] = to;
          spell[1] = toRoman(total);
        }
      });
    }
    if (sheet.Spells) {
      patch('Innoculate', 'Inoculate');
      patch('Tonsilectomy', 'Tonsillectomy');
    }
  }
  ,
  // 1 -> 2: combat. Characters now have current HP and MP.
  function (sheet) {
    var hp = parseInt(sheet.Stats['HP Max'], 10) || 0;
    var mp = parseInt(sheet.Stats['MP Max'], 10) || 0;
    sheet.HPBar = { position: hp, max: hp };
    sheet.MPBar = { position: mp, max: mp };
  },
  // 2 -> 3: loot. Gear power is stored as a number (read from the item
  // names here), and gold found on the Killing Fields is carried in a purse
  // until it is banked at market.
  function (sheet) {
    sheet.EquipPower = {};
    if (typeof GearPower === "function") {
      $.each(K.Equips, function (i, slot) {
        var name = sheet.Equips ? sheet.Equips[slot] : '';
        sheet.EquipPower[slot] = slot == 'Weapon' ?
          GearPower(name, K.Weapons, K.OffenseAttrib, K.OffenseBad) :
          GearPower(name, slot == 'Shield' ? K.Shields : K.Armors, K.DefenseAttrib, K.DefenseBad);
      });
    }
    sheet.purse = sheet.purse || 0;
  },
  // 3 -> 4: defeat. Count of defeats, and fights left Wounded.
  function (sheet) {
    sheet.deaths = sheet.deaths || 0;
    sheet.wounded = sheet.wounded || 0;
  },
  // 4 -> 5: stories. Each Act gets a story when it begins (the current
  // one is picked when the save loads; see EnsureStory in main.js).
  function (sheet) {
    sheet.storyLog = sheet.storyLog || [];
  },
  // 5 -> 6: event buffs (temporary stat boosts) and the last event.
  function (sheet) {
    sheet.buffs = sheet.buffs || [];
    sheet.recentEvent = sheet.recentEvent || null;
  }
];

function MigrateSave(sheet) {
  var v = sheet.saveVersion || 0;
  if (v > SaveVersion)
    throw new Error("This character was saved by a newer version of Progress Quest Remix (save v" +
                    v + ", this is v" + SaveVersion + ").");
  for (; v < SaveVersion; ++v)
    SaveMigrations[v](sheet);
  sheet.saveVersion = SaveVersion;
  return sheet;
}

var K = {};

K.Traits = ["Name", "Race", "Class", "Level"];

K.PrimeStats = ["STR","CON","DEX","INT","WIS","CHA"];
K.Stats = K.PrimeStats.slice(0).concat(["HP Max","MP Max"]);

// Attribute profiles
// ------------------
// Every race and class lists a primary and a secondary attribute
// ("Name|PRIMARY,SECONDARY"). A character's profile adds them up: the
// primary is worth K.PrimaryWeight, the secondary K.SecondaryWeight, and
// an attribute listed by both race and class counts twice.
K.PhysicalStats = ["STR","CON","DEX","HP Max"];
K.ArcaneStats   = ["INT","WIS","CHA","MP Max"];
K.PrimaryWeight = 2;
K.SecondaryWeight = 1;

// How strongly a profile attribute is favored when a stat point is won.
// Every stat starts at K.StatPickBase, plus its profile weight, so with the
// defaults a primary is picked 5:3 as often as an unlisted stat and a
// secondary 4:3. Lower it for a stronger bias (2 makes a primary 2:1).
K.StatPickBase = 3;

// Extra HP/MP on level-up, in percent per point of profile weight, when
// HP Max or MP Max is in the profile (primary +20%, secondary +10%).
K.PoolGrowthPerWeight = 10;

// The tags of a race or class by name, e.g. ["STR","INT"]; [] if unknown.
function StatTags(list, name) {
  for (var i = 0; i < list.length; ++i) {
    var parts = list[i].split("|");
    if (parts[0] === name)
      return parts[1] ? parts[1].split(",") : [];
  }
  return [];
}

// Profile of a race/class combination:
//   weights      { stat: weight } for every stat in K.Stats (0 if unlisted)
//   primary      stats that are a primary for the race or the class
//   secondary    stats that are a secondary (and not also a primary)
//   physical     total weight on K.PhysicalStats
//   arcane       total weight on K.ArcaneStats
//   physicality  physical / (physical + arcane): 1 is pure brawn, 0 is pure
//                magic. 0.5 if the race and class are both unknown.
function AttributeProfile(race, klass) {
  var weights = {};
  $.each(K.Stats, function (i, stat) { weights[stat] = 0; });
  var primary = [], secondary = [];
  $.each([StatTags(K.Races, race), StatTags(K.Klasses, klass)], function (i, tags) {
    $.each(tags, function (j, stat) {
      if (!(stat in weights)) return;
      weights[stat] += j === 0 ? K.PrimaryWeight : K.SecondaryWeight;
      if (j === 0) {
        if (primary.indexOf(stat) < 0) primary.push(stat);
      } else if (secondary.indexOf(stat) < 0) {
        secondary.push(stat);
      }
    });
  });
  secondary = secondary.filter(function (s) { return primary.indexOf(s) < 0; });

  var physical = 0, arcane = 0;
  $.each(K.PhysicalStats, function (i, s) { physical += weights[s]; });
  $.each(K.ArcaneStats, function (i, s) { arcane += weights[s]; });
  return {
    weights: weights,
    primary: primary,
    secondary: secondary,
    physical: physical,
    arcane: arcane,
    physicality: (physical + arcane) ? physical / (physical + arcane) : 0.5
  };
}

// "Martial 67% / Arcane 33%"
function ProfileSummary(profile) {
  var m = Math.round(100 * profile.physicality);
  return "Martial " + m + "% / Arcane " + (100 - m) + "%";
}

K.Equips = ["Weapon",
            "Shield",
            "Helm",
            "Hauberk",
            "Brassairts",
            "Vambraces",
            "Gauntlets",
            "Gambeson",
            "Cuisses",
            "Greaves",
            "Sollerets"];

// From 47 to 406 spells
// Each spell is "Name|type". The type sets what it does in a fight:
//   damage  hurts the monster (INT)
//   heal    restores your HP (WIS)
//   buff    you hit harder and take less damage for the rest of the fight
//   debuff  the monster hits softer and takes more damage
//   cc      crowd control: the monster loses turns (CHA to land it)
// A spell with no type gets a random one, always the same for that name.
K.Spells = [
  "Mostly True Seeing|buff",
  "Gravity Stinkhole|cc",
  "Just Danse Macabre|cc",
  "Nystul's Magic Fedora|buff",
  "Tumor (Malignant)|damage",
  "Passive Aggressive Lockjaw|cc",
  "Necrophilia-mancy|damage",
  "50 Shades of Greyskull|buff",
  "Foreskin-sight|buff",
  "Stinking Cloud Computing|cc",
  "Otto's Irresistible Lap Dance|cc",
  "Prismatic Fray|damage",
  "Meatier Swarm|damage",
  "Vitreous Humor|debuff",
  "Time Stop Hammer Time|cc",
  "Green-Flame Blade Runner|damage",
  "Speak with Dead Kennedys|buff",
  "Cooties Inoculate|buff",
  "Banishing Smite the Bullet|damage",
  "Wall of Ring of Fire|damage",
  "Witch Bolt Action Rifle|damage",
  "Linger of Death|damage",
  "Cause Fear Factory|cc",
  "Kitchen Counterspell|cc",
  "Squid Pro Quo|debuff",
  "Magnetic Orb|damage",
  "Mage Under Armor|buff",
  "Vortex Time Warp|cc",
  "Wheel of Fortune's Favor|buff",
  "Silent Chill Touch|damage",
  "Jurassic Barkskin|buff",
  "Ursine Armor|buff",
  "Stone Shape of Water|buff",
  "Dominatrix Monster|cc",
  "Silent Butt Deadly Image|debuff",
  "Enhance Futility|buff",
  "Ooze of Questionable Origin|debuff",
  "Fingering of Death|damage",
  "Sacred Flambé|damage",
  "Seasick|debuff",
  "Remove Blurse|heal",
  "Whirl Wind Beneath My Wings|damage",
  "Battlefield Earthquake|damage",
  "Earthen Grasp and the Furious|cc",
  "Pink Floyd's The Wall of Fire|damage",
  "Identify Gently-Used Corpse Loot|buff",
  "Minor Collusion|cc",
  "Animal Friend-zone-ship|cc",
  "Find Google Traps|cc",
  "Poison Ocean Spray|debuff",
  "Infinite Confusion|cc",
  "Burning Glands|damage",
  "Holy Roller|damage",
  "Sneezing Sphere|debuff",
  "Ray of Emma Frost|damage",
  "Vampiric Touch Ado About Nothing|damage",
  "Ectoplasmic Horny Jail|cc",
  "Thunder Step-Sibling Porn|damage",
  "Dropsy Drop Bear|damage",
  "Word of Total Recall|buff",
  "Holy Weapon of Math Destruction|damage",
  "History Lesson|cc",
  "Ethe-Loreal-ness|buff",
  "Aqueous Humor|heal",
  "Redneck Plague|debuff",
  "Conjure Pointy Bits|damage",
  "Arcane Eye-Phone|buff",
  "Collect Call Lightning|damage",
  "Hydrophobia|cc",
  "Create Food and Waterslide|heal",
  "+10 to Sexterity|buff",
  "Astral Miasma|debuff",
  "Scrying Your Eyes Out|debuff",
  "Spectral Miasma Marinara|debuff",
  "Hastiness|buff",
  "Locate Creature Comforts|heal",
  "Tiny Pizza Hut|heal",
  "Inflict Prunes|debuff",
  "Tasha's Otherworldly Five Guys|heal",
  "Ray of Down with the Sickness|debuff",
  "Healing Whirred|heal",
  "Braingate|debuff",
  "Wind Wonderwall|cc",
  "Heat Meal Gear Solid|damage",
  "Gravity Anal Fissure|damage",
  "Dog the Bounty Hunter's Mark|debuff",
  "Sierra Misty Step|buff",
  "Mordenkainen's Faithful Clown|buff",
  "Feather Fall of Duty|buff",
  "Scold Person|cc",
  "Magic Bristle|damage",
  "Choke a Bitch|cc",
  "Word of Pool of Radiance|damage",
  "Discount Llama Companion|buff",
  "Notre Flame Arrows|damage",
  "Project Scrimmage|cc",
  "Curse Family|debuff",
  "Mass Effect Suggestion|cc",
  "Boston Globe of Invulnerability|buff",
  "Curse Name|debuff",
  "Thorn Miracle Whip|damage",
  "Donkey Punch|damage",
  "Black Idaho|cc",
  "Infernal Calling Card|damage",
  "Saturday Blight Live|damage",
  "Igor's Itchy Undergarments|debuff",
  "Plane Thrift|buff",
  "Floating Disk Drive|buff",
  "Shoelaces|cc",
  "Dimension Doorbell|buff",
  "Mike's Hard Lemonade|heal",
  "Premature Evocation|damage",
  "Grasping Vines and TikToks|cc",
  "Summon Beast Germany|damage",
  "Blink-182|buff",
  "Somewhat-Good-Berry|heal",
  "Ice Cream Cone of Cold|damage",
  "Eye of the Troglodyte|debuff",
  "Scorching Rachel Ray|damage",
  "Eldritct Baja Blast|damage",
  "Pantalones Giganticus|buff",
  "Blunderwave|damage",
  "Shadow the Hedgehog Blade|damage",
  "Divine Flavor|buff",
  "For Crying Out Cloudkill|damage",
  "Gaseous this isn't even my Final Form|buff",
  "Chaos Emerald Bolt|damage",
  "Fire Usain Bolt|damage",
  "Surprise Surgery|heal",
  "Circle of Power Ranger|buff",
  "Swear the Dying|heal",
  "Greator or less than Restoration|heal",
  "Beauty and the Beast Sense|buff",
  "Tonsillectomy|damage",
  "Power Word Kill Gates|damage",
  "Friar-ball|damage",
  "Tensor's Floating Disk Drive|buff",
  "Portal to Elemental Plane of Gravy|cc",
  "Stoned Skin|buff",
  "Braise Dead|damage",
  "Incenidiary Cloud Nine|damage",
  "Feeblemind Over Matter|debuff",
  "Disguise Shelf|buff",
  "Sickening Miscellaneous|debuff",
  "Toll the Dead Hot Chili Peppers|damage",
  "Flicum Bicus|damage",
  "Grind Familiar|buff",
  "Slime Finger|debuff",
  "Grognor's Big Day Off|heal",
  "Psychic Scream VI|cc",
  "Frobnitz Frobnosia Xyzzy|cc",
  "Dissonant Careless Whispers|damage",
  "Tasha'a Mind Cool Whip|damage",
  "Icy Hot Knife|damage",
  "Thunder The Clap|damage",
  "Holy Batpole|damage",
  "Ensnaring Sike|cc",
  "Detect Tragic|buff",
  "Invisible Glands|buff",
  "Not-quite Invulnerability|buff",
  "Sun Burst-Person Shooter|damage",
  "Tasha's Hideous Shafter|cc",
  "Greased Chain Lightning|damage",
  "Milf's Acid Hard Shaft|damage",
  "Transmute Dwayne The Rock Johnson|buff",
  "Inflict Crotch Rot|debuff",
  "Modify Memory-foam|cc",
  "Mind Spike Lee|damage",
  "Acrid Hands|damage",
  "Cone of Paste|cc",
  "Gelatinous Cube Jenga|cc",
  "Freedom of Bowel Movement|buff",
  "Wrath of Khan of Nature|damage",
  "Summon a Bitch|damage",
  "Blur Wounds|buff",
  "Tumor (Benign)|debuff",
  "Power Word House of Pain|damage",
  "Roger's Bland Illusion|cc",
  "Faerie Fireball Whiskey|damage",
  "Mage Gland|buff",
  "Wombats All the Way Down|damage",
  "Right to OwlBear Arms|buff",
  "Hocus Pocus In Loco Parentis|debuff",
  "Smarm Person|cc",
  "Spectral Oyster|damage",
  "Rebecca Black Tentacles|cc",
  "Animate Nightstand|damage",
  "Swiss Army Life Transference|heal",
  "Choke-Hold Person|cc",
  "Angioplasty|heal",
  "Cone of Annoyance|debuff",
  "Peeled of Faith|buff",
  "Biggus Dickus Energus|buff",
  "Dancing Tights|cc",
  "Spiritual Lethal Weapon|damage",
  "Nonplus|cc",
  "Frammin' on the jim-jam|debuff",
  "Dispel Magic Kingdom|debuff",
  "Acid Splash Gordon|damage",
  "Poly-amorous-morph|cc",
  "True Lies Seeing|buff",
  "Clever Fellow|buff",
  "Swift Quivering Loins|buff",
  "BarryWhiteus candlelightus girl-exciteus|cc",
  "Nuclear Power Plant Growth|damage",
  "Anti-tragic Field|buff",
  "Conjure Instumental|cc",
  "Alter Elf|buff",
  "Three Wolf Moon Beam|damage",
  "Lightning Broken Arrow|damage",
  "Bigby's Hand Sanitizer|heal",
  "Sadness|debuff",
  "Foregone Illusion|cc",
  "Pre-stud-agitation|buff",
  "Nestor's Bright Idea|buff",
  "Vicious Colin Mochrie|debuff",
  "Water Walk Like an Egyptian|buff",
  "Melf's Acid Reflux|damage",
  "Bigby's Inappropriate Hand|cc",
  "Tasha's Caustic Remark|debuff",
  "Evard's Tickling Tentacles|cc",
  "Leomund's Subprime Mortgage|debuff",
  "Rope Trick-or-Treat|buff",
  "Pass Without a Trace of Dignity|buff",
  "Cone of Lukewarm|damage",
  "Summon Greater Caucasian|debuff",
  "Crown of Madness: Fury Road|cc",
  "Glibness (Corporate Edition)|buff",
  "Geas Lightning|damage",
  "Animate Deadbeat Dad|damage",
  "Vicious Mockery of Justice|debuff",
  "Guiding Lite Beer|buff",
  "Misty Step-Father|buff",
  "Chain Smoking Lightning|damage",
  "Phantasmal Killer Queen|damage",
  "Hold Person hostage|cc",
  "Power Word Chill|cc",
  "Power Word Spill|debuff",
  "Wall of Text|cc",
  "Spiritual Sidearm|damage",
  "Speak with Animals (Unsolicited)|buff",
  "Banishment to Gary, Indiana|cc",
  "Arcane Lockout|cc",
  "Detect Mild Disapproval|debuff",
  "Color Spray Tan|cc",
  "Blink-and-You-Miss-It|buff",
  "Antilife Shellfish Allergy|debuff",
  "Mirror Image Issues|buff",
  "Locate Car Keys|buff",
  "Uncontrollable Flatulence|debuff",
  "Tenser's Floating Keg|heal",
  "Gentle Repose in Peace|heal",
  "Zone of Brutal Honesty|debuff",
  "Chill Touch of Gray|damage",
  "Delayed Blast Fire Marshall|damage",
  "Finger of Mild Discomfort|damage",
  "Spare the Dying of Embarrassment|heal",
  "Sending 'U up?'|cc",
  "Mass Suggestion Box|cc",
  "Otiluke's Resilient Bubble Wrap|buff",
  "Beacon of Hope Solo|heal",
  "Polymorph into a Moderately Priced Sedan|cc",
  "Conjure Woodland HOA|debuff",
  "Eyebite the Curb|cc",
  "Prismatic Spray-on Deodorant|buff",
  "Holy Waterboard|damage",
  "Find Traps in the Contract|buff",
  "Comprehend Broken Spanglish|buff",
  "Ray of Enfeeble-Mint Gum|debuff",
  "Dispel Mojo|debuff",
  "Crushing Despair (Clinically Diagnosed)|debuff",
  "Drawmij's Instant Regret|debuff",
  "Rary's Telepathic Conference Call|cc",
  "Feign Death to Avoid Conversation|heal",
  "Snilloc's Snowball Fight|damage",
  "Aganazzar's Hot Pocket Scorcher|damage",
  "Maximilian's Earthen Fistbump|damage",
  "Jim's Glowing Magic Coin|buff",
  "Flock of Karens|debuff",
  "Galder's Speedy Delivery|heal",
  "Summon Underpaid Intern|buff",
  "Nathair's Mischievous Tax Fraud|debuff",
  "Ashardalon's Heartburn|damage",
  "Fizban's Platinum Credit Card|buff",
  "Blade Ward Cleaver|buff",
  "True Strike Three|buff",
  "Guidance Counselor|buff",
  "Thorn Whip-It|damage",
  "Mind Sliver of Hope|damage",
  "Primal Savagery Gardens|damage",
  "Sword Burst-a-Move|damage",
  "Thunderclap of Doom-scrolling|damage",
  "Inflict Papercuts|damage",
  "Cure Moderate Hangover|heal",
  "Expeditious Retreat to the Bathroom|buff",
  "Arms of Little Caesar|damage",
  "Chaos Bolt-on Exhaust|damage",
  "Heroism at Clearance Price|buff",
  "Witch Bolt 45|damage",
  "Zephyr Strike a Pose|buff",
  "Barkskinny Dipping|buff",
  "Flame Blade Trinity|damage",
  "Spike Growth Hormone|damage",
  "Cloud of Daggers (Plastic)|damage",
  "Crown of Thorns and Roses|damage",
  "Darkness My Old Friend|cc",
  "Enthrall of the Wild|cc",
  "Levitate Suspiciously|buff",
  "Spider Climb into Bed|buff",
  "Hypnotic Pattern Baldness|cc",
  "Slow and Steady Wins the Race|debuff",
  "Call Lightning Charging Cable|damage",
  "Conjure Barrage of Excuses|damage",
  "Hunger of Hadar's Kitchen|debuff",
  "Melf's Minute Minute Maid|damage",
  "Tiny Servant (Minimum Wage)|buff",
  "Compulsion Shopping|cc",
  "Confusion Matrix|cc",
  "Dimension Doorknob|buff",
  "Fabricate Evidence|debuff",
  "Giant Insect Repellent|buff",
  "Ice Stormy Daniels|damage",
  "Locate Restroom|heal",
  "Phantasmal Killer Whale|damage",
  "Stone Shape of You|buff",
  "Watery Sphere of Influence|cc",
  "Cloudkill Joy|damage",
  "Commune with Dead Relatives for Money|buff",
  "Contact Other Plane Ticket|buff",
  "Contagion Warning|debuff",
  "Danse Macarena|cc",
  "Destructive Wave Goodbye|damage",
  "Geas by the Throttle|cc",
  "Hold Monster Energy|cc",
  "Insect Plague of Locust Valley|damage",
  "Mislead Singer|cc",
  "Modify Memory Leak|debuff",
  "Reincarnate as a Beetle|heal",
  "Scrying Out Loud|buff",
  "Seeming Legit|buff",
  "Telekinesis Pillow Fight|damage",
  "Teleportation Circle Jerk|buff",
  "Transmute Rock to Pop|debuff",
  "Wall of Stone Cold Steve Austin|cc",
  "Chain Lightning McQueen|damage",
  "Circle of Death Metal|damage",
  "Create Undead Broke|debuff",
  "Disintegrate into Tears|damage",
  "Eyebite-sized Snickers|heal",
  "Flesh to Styrofoam|cc",
  "Freezing Sphere of Influence|damage",
  "Guards and Wards Wardrobe Malfunction|debuff",
  "Harm's Way|damage",
  "Heal the World|heal",
  "Heroes' Feast of Lean Cuisines|heal",
  "Magic Jar Jar Binks|debuff",
  "Mass Suggestion Engine|cc",
  "Otto's Irresistible Macaroni|cc",
  "Programmed Illusion of Choice|cc",
  "Sunbeam Me Up Scotty|damage",
  "True Seeing Red|buff",
  "Delayed Blast Taco Bell|damage",
  "Fire Stormtrooper|damage",
  "Mirage Arcane Candy|cc",
  "Mordenkainen's Magnificent Airbnb|heal",
  "Plane Shift into Reverse|cc",
  "Prismatic Spray Paint|damage",
  "Project Imageboard|cc",
  "Regenerate Teeth|heal",
  "Resurrection Shuffle|heal",
  "Reverse Gravity Bong|cc",
  "Sequestered Jury|cc",
  "Simulacrum of Truth|buff",
  "Symbol of Status|buff",
  "Teleport to Nearest Wendy's|heal",
  "Whirlwind Romance|cc",
  "Animal Shapes and Sizes|buff",
  "Antipathy-Sympathy Card|debuff",
  "Clone High|buff",
  "Control Weather Underground|damage",
  "Demiplane of Cheap Wine|heal",
  "Dominate Monster Truck|cc",
  "Earthquake Shake|damage",
  "Feeblemind Game|debuff",
  "Holy Aura Borealis|buff",
  "Incendiary Cloudflare|damage",
  "Maze Runner|cc",
  "Mind Blank Slate|buff",
  "Power Word Stun Gun|cc",
  "Power Word Shart|debuff",
  "Sunburst Fruit Chew|damage",
  "Astral Projection Screen|buff",
  "Foresight is 20/20|buff",
  "Gate Crash|damage",
  "Imprisonment Without Trial|cc",
  "Mass Heal the World|heal",
  "Meteor Swarm of Angry Bees|damage",
  "Power Word Killjoy|debuff",
  "Prismatic Wall of Sound|damage",
  "Shapechange My Mind|buff",
  "Time Stop Collaborate and Listen|cc",
  "Time Stop in the Name of Love|cc",
  "True Polymorph into a Roomba|cc",
  "Weird Flex But OK|buff",
];

// from 11 to 102 Offensive Attributes
K.OffenseAttrib = [
  "Not-Shabby|+1",
  "Somewhat-Sharp|+1",
  "Mostly-Clean|+1",
  "Kinda-Solid|+1",
  "Hardly-Rusted|+1",
  "Adequate|+1",
  "Pointy-ish|+1",
  "Barely-Tetanus-Free|+1",
  "Passably-Sturdy|+1",
  "Slightly-Menacing|+1",
  "Better-Than-A-Stick|+1",
  "Tolerably-Pointed|+1",
  "Cleaned-With-Spit|+1",
  "Dented-But-Functional|+1",
  "Wobbly-Shafted|+1",
  "Heftsome|+2",
  "Pain-Inducing|+2",
  "Multi-stabby|+2",
  "Steely|+2",
  "Stingy|+2",
  "Poke-Tastic|+2",
  "Aggressively-Heavy|+2",
  "Splinter-Infused|+2",
  "Thwack-Happy|+2",
  "Bruise-Prone|+2",
  "Ouchy|+2",
  "Semi-Lethal|+2",
  "Shin-Kicking|+2",
  "Rib-Tickling|+2",
  "Uncomfortably-Pointed|+2",
  "Spleen-Seeking|+3",
  "Nasty-Tempered|+3",
  "Groin-Punting|+3",
  "Toe-Stubbing|+3",
  "Mildly-Cursed|+3",
  "Flesh-Parting|+3",
  "Smack-Worthy|+3",
  "Sinister-Looking|+3",
  "Subtly-Glowy|+3",
  "Ankle-Whacking|+3",
  "4chan-Troll-Slaying|+3",
  "Hurtful|+3",
  "Magicalastic|+3",
  "Decidedly-Unfriendly|+3",
  "Vicious|+3",
  "Bitch-Smacking|+4",
  "Enchantified|+4",
  "Venomed|+4",
  "Stabbity|+4",
  "Giggle-Slicing|+4",
  "Gore-Splattered|+4",
  "Kneecap-Cracking|+4",
  "Spiky-McSpikerson|+4",
  "Kidney-Piercing|+4",
  "Rage-Fueled|+4",
  "Over-Enchanted|+4",
  "Skull-Concussing|+4",
  "Spleen-Vented|+4",
  "Gut-Wrenching|+4",
  "Hackmaster|+5",
  "En Fuego|+5",
  "Dirty-Dancing|+5",
  "Forceful|+5",
  "Face-Melting|+5",
  "Excessively-Sharpened|+5",
  "Blood-Spattering|+5",
  "Ass-Kicking|+5",
  "Brimstone-Laced|+5",
  "Unnecessarily-Spiky|+5",
  "Viscera-Churning|+5",
  "Throat-Cleaving|+5",
  "Gloom-Forged|+5",
  "Limb-Decoupling|+5",
  "Holy-Forkballs|+6",
  "Invisible|+6",
  "Talking|+6",
  "Mighty|+6",
  "Soul-Devouring|+6",
  "Mother-In-Law-Grade|+6",
  "Screaming-In-Tongues|+6",
  "Meme-Tier|+6",
  "Slightly-Sentient|+6",
  "Thunder-Thumping|+6",
  "Cranial-Caving|+6",
  "Apocalyptic-ish|+6",
  "Doomsday-Lite|+6",
  "Blindingly-Shiny|+6",
  "Vorpal|+7",
  "Puissant|+7",
  "Ginormous|+7",
  "Adamantine|+7",
  "Nigh-Omnipotent|+7",
  "Server-Crashing|+7",
  "Universe-Dentingly-Sharp|+7",
  "DM-Infuriating|+8",
  "Reality-Sundering|+8",
  "Physics-Defying|+8",
  "God-Smiting|+9",
  "Game-Breaking|+9",
  "One-Shot-Wonder|+9",
  "RNGesus-Blessed|+10",
  "Bribed-the-GM|+10",
];

// from 9 to 102 Defensive Attributes
K.DefenseAttrib = [
  "Form-Fitted|+1",
  "Star-Studded|+1",
  "Mostly-Solid|+1",
  "Pillow-Fortified|+1",
  "Color-Coordinated|+1",
  "Duct-Taped|+1",
  "Cardboard-Reinforced|+1",
  "Bubble-Wrapped|+1",
  "Slightly-Padded|+1",
  "Tough-As-Jerky|+1",
  "Stain-Resistant|+1",
  "Double-Stitched|+1",
  "Sweat-Wicking|+1",
  "Wrinkle-Free|+1",
  "Pinch-Proof|+1",
  "Travelocity-Gnome-Made|+2",
  "Bedazzled|+2",
  "Band-aid-ed|+2",
  "Gilded|+2",
  "Officially-Licensed|+2",
  "Scotchgard-Treated|+2",
  "Flex-Sealed|+2",
  "As-Seen-On-TV|+2",
  "Velcro-Fastened|+2",
  "WD-40-Lubed|+2",
  "Ergonomic|+2",
  "Snuggly-Fitted|+2",
  "Polite-Looking|+2",
  "Faux-Leather-Lined|+2",
  "Blinged-Out|+2",
  "Shelven|+3",
  "Magicalastic|+3",
  "Cambric|+3",
  "Thematically Appropriate|+3",
  "Festooned|+3",
  "Chic-Yet-Defensive|+3",
  "Linoleum-Plated|+3",
  "Non-Stick-Coated|+3",
  "Hermetically-Sealed|+3",
  "Aerodynamic|+3",
  "Artisanal-Forged|+3",
  "Snazzy|+3",
  "Reinforced-Gore-Tex|+3",
  "Puffer-Vested|+3",
  "Over-Engineered|+3",
  "Holy|+4",
  "Fine-Ass|+4",
  "Krystal|+4",
  "Enchantified|+4",
  "Rubber-Bumpered|+4",
  "Deflect-O-Matic|+4",
  "Cast-Iron-Seasoned|+4",
  "Shamelessly-Bulky|+4",
  "Shock-Absorbing|+4",
  "Glow-in-the-Dark|+4",
  "Reflective-Safety|+4",
  "Bullet-Dodgey|+4",
  "Spiky-Shielded|+4",
  "Repellant-Scented|+4",
  "Mithrallic|+5",
  "Mecha|+5",
  "Impressive|+5",
  "Unyielding|+5",
  "Adamantastic|+5",
  "Bespoke-Chitin|+5",
  "Tungsten-Reinforced|+5",
  "Cast-Iron-Skillet|+5",
  "Nokia-3310-Cased|+5",
  "Heavy-Duty-Industrial|+5",
  "Explosion-Proof|+5",
  "Armor-All-Dipped|+5",
  "Dwarven-Overbuilt|+5",
  "Stab-Deflecting|+5",
  "Diamond-Encrusted|+6",
  "Most-Impressive|+6",
  "Kevlar|+6",
  "Impenetrable|+6",
  "Plot-Armored|+6",
  "Bank-Vault-Grade|+6",
  "Titanium-Encrusted|+6",
  "Forcefield-Adjacent|+6",
  "Bubble-Boy-Grade|+6",
  "Cringe-Deflecting|+6",
  "Insufferably-Sturdy|+6",
  "Vibranium-Flavored|+6",
  "Gargantuan-Plated|+6",
  "Hazard-Suited|+6",
  "Phase-Shifting|+7",
  "Unobtanium|+7",
  "Unassailable|+7",
  "Pay-to-Win|+7",
  "Save-Scummed|+7",
  "Invulnerabilicious|+7",
  "Nerf-Immune|+7",
  "Hitbox-Displacing|+7",
  "Subscription-Tier|+8",
  "Cheat-Coded|+8",
  "DM-Proof|+8",
  "Dev-Console-Forged|+9",
  "Main-Character-Syndrome|+9",
  "God-Mode-Toggled|+10",
  "Bribed-the-GM|+10",
];

// from 16 to 164 Shields
K.Shields = [
  "Parasol|0",
  "Paper Hand Fan|0",
  "Cocktail Umbrella|0",
  "Cardboard Coaster|0",
  "Bubble Wrap Mailer|0",
  "Soggy Pizza Box|1",
  "Pie Plate|1",
  "Crusty Mousepad|1",
  "Cafeteria Tray|1",
  "Tupperware Lid|1",
  "Garbage Can Lid|2",
  "Half-Chewed Frisbee|2",
  "Baking Sheet|2",
  "Hubcap|2",
  "Expired Coupon Mailer|2",
  "Foam LARP Shield|3",
  "Belt Buckler|3",
  "Clipboard of Authority|3",
  "Stop Sign|3",
  "Sledding Saucer|3",
  "Pot Lid|4",
  "Plexiglass|4",
  "Fender|4",
  "Wok of Ages|4",
  "Cast-Iron Skillet|4",
  "Paula Deen Butter Tray|4",
  "Woody Shield|5",
  "Ground Round Shield|5",
  "Lazy Susan|5",
  "Cutting Board of Truth|5",
  "Travelocity Roaming Gnome Buckler|5",
  "VW Beetle Carapace|6",
  "Bronzer Shield|6",
  "Ironing Board Tower Shield|6",
  "Kegerator Cover|6",
  "Spruce Goose Wing Section|6",
  "Roman Scutum|7",
  "Carriage Door|7",
  "Pinball Playfield Glass|7",
  "Derrick Door|7",
  "Sump Pump Lid|7",
  "Manhole Cover|8",
  "Propugner|8",
  "Storm Door with Screen|8",
  "Bass Drumhead|8",
  "Chamberpot Lid|8",
  "Steel Space Heater|9",
  "Kite Shield|9",
  "Smiley Face Shield|9",
  "Turtle Shell Phone|9",
  "Spiked Buckler of Pretzel Biting|9",
  "4Chan Troll Bone Shield|10",
  "Pavise|10",
  "Trash Compactor Door|10",
  "Space Invader Shield|10",
  "Riot Control Polycarb|10",
  "Spiked Hard Shield|11",
  "Solar Tower Shield|11",
  "Stonecutter Guild Plaque|11",
  "Lead-Lined Apron|11",
  "Turtle Waxed Targe|11",
  "Baroque Shield|12",
  "Spiked Pavise|12",
  "Cap'n Americool Knock-off Shield|12",
  "Bouncing Buckler|12",
  "Titanium Waffle Iron|12",
  "Ballistic Shield|13",
  "Graphene Glider Wing|13",
  "Hover-Board Plating|13",
  "Reinforced Bank Teller Glass|13",
  "Deflect-o-Matic|14",
  "Nokia 3310 Backplate|14",
  "Shed Door of Fortitude|14",
  "Segway Baseplate|14",
  "Hylian Shield|15",
  "Shield of the Silver Surfer|15",
  "Bad Dragon Scale Buckler|15",
  "Lead-Shielded Dental Apron|15",
  "Shield Knight Shield|16",
  "Ablative Microwave Door|16",
  "Ankh-Morpork Crest|16",
  "Subway Turnstile Arm|16",
  "Brick Wall|17",
  "Cyberman Sternum Plate|17",
  "Force-Field Generator (Refurbished)|17",
  "Titan-Anium Shield|18",
  "Solid State Drive Shield|18",
  "Spam Can Vault Wall|18",
  "Vibra-Adamantium Shield|19",
  "Beskar Dustbin|19",
  "Bulwark of Pure Irony|19",
  "Greatshield of Fartorias|20",
  "Greatshield of Havel the Rock Johnson|20",
  "Tower of Babel Brick|20",
  "Shield of Achilles|21",
  "Shield of the High Treant|21",
  "Brave Sir Robin's Crest|21",
  "Shield of Aeneas|22",
  "Gorgon's Makeup Mirror|22",
  "Trollface Tower Shield|22",
  "Pridwin|23",
  "Mirror Shield of Narcissus|23",
  "Great Wall of China Replica|23",
  "Ochain|24",
  "Bravado Barrier|24",
  "Eternium Heater|24",
  "Svalinn|25",
  "Ancile of Mars|25",
  "Aegis|26",
  "Dubious Plot Aegis|26",
  "Gungnir-Deflecting Pavise|26",
  "Magnetic Field|27",
  "Event Horizon|27",
  "Dark Energy Screen|27",
  "Tachyon Deflector|28",
  "End-User License Agreement|28",
  "Cap'n America Vibranium Disc|28",
  "Terms of Service Pop-up|29",
  "Firewall of China|29",
  "Turing Test Wall|29",
  "Shield of Infinite Buffers|30",
  "Fortress of Solitude Doorstop|30",
  "Unbroken NDAs|30",
  "DM Screen of Absolute Secrecy|31",
  "Zero-Point Energy Wall|31",
  "God-Mode Hex Grid|32",
  "Hard-Light Construct|32",
  "Schrödinger's Deflector Plate|33",
  "Antimatter Mirror|33",
  "Mithril Vault Hatch|34",
  "Dyson Swarm Shingle|34",
  "Quantum Uncertainty Screen|35",
  "Borg Personal Shield Adaptor|35",
  "Beskar Blast Door|36",
  "Tesseract Barrier|36",
  "Plot Inconvenience Barrier|37",
  "Plasma Window Generator|37",
  "Dimensional Fold Shield|38",
  "Neutronium Manhole Cover|38",
  "Infinity Gauntlet Backplate|39",
  "Anti-Magic Pentagon|39",
  "Mirror of Utter Indifference|40",
  "Warp Core Containment Field|40",
  "Singularity Ward|41",
  "Chrono-Lock Buckler|41",
  "Two-Factor Authentication Wall|42",
  "Server Rack Front Panel|42",
  "The Fourth Wall|43",
  "Axiomatic Repulsor|43",
  "Infinite Loop Shielding|44",
  "Git Revert Shield|44",
  "Deus Ex Machina Pavise|45",
  "Cheat Engine Membrane|45",
  "Big Bang Afterglow Deflector|46",
  "Subspace Anomaly Barrier|46",
  "Save-State Anchor|47",
  "Unbreakable DRM Wall|47",
  "Admin Override Scutum|48",
  "Developer Console Forcefield|48",
  "Stack Overflow Bulkhead|49",
  "Omnipotent Parody Aegis|49",
  "Source Code Firewall|50",
  "The Ultimate Plot Armor Greatshield|50",
];

// from 20 to 145 Armors
K.Armors = [
  "Chantilly and Lace|1",
  "Wet T-Shirt|1",
  "Spit-Shined Napkin|1",
  "Toilet Paper Poncho|1",
  "Macrame Jockstrap|2",
  "Padded Cell Armor|2",
  "Fruit of the Loom Briefs|2",
  "Mummy Dearest Gauze Wrap|2",
  "Iron Maiden Shirt|3",
  "Burlap Sack|3",
  "Cardboard Golem Cutout|3",
  "Feral Muppet Felt Jerkin|3",
  "Pop-Tart Wrapper Vest|3",
  "Oil on Canvas|4",
  "Bikini Chain Mail|4",
  "Fishnet Bodysuit of Frank N Furter|4",
  "Barbie Devil Flame Bikini|4",
  "Bubble Wrap Onesie|4",
  "Stiff Dirty Laundry|5",
  "Grungy Flannel|5",
  "Dirty Laundry Golem Hoodie|5",
  "Stray Cat Fur Coat|5",
  "Hide and Seek Armor|6",
  "Outlaw Chamois Loofah|6",
  "Grassy Gnoll Camo Suit|6",
  "Bed-Bug-Bear Pelts|6",
  "Sweaty Pleathers|7",
  "Gambeson|7",
  "Drop Bear Hide Vest|7",
  "Aware-Wolf Leather Jacket|7",
  "Stud Leather|8",
  "Kinky Leathers|8",
  "Double-Wookiee Shag Jerkin|8",
  "Padded Cell Linoleum Cuirass|8",
  "Sharkasaurus Leather Studs|8",
  "Chain Polo Shirt|9",
  "Care Bearskin|9",
  "Soda Can Tab Ringmail|9",
  "Rusty Chainlink Fence Mail|9",
  "Lamellar Armor|10",
  "Lord of the Ringmail|10",
  "Ankylosaurus Nugget Scale|10",
  "Paperback Fighter Paperback Armor|10",
  "Rust Monster Chitin Vest|10",
  "Full Fursuit|11",
  "Briga-Paula-Deen|11",
  "Canadian Tuxedo Denim Mail|11",
  "High Treant Barkskin Mail|11",
  "Kinsey Scale Mail|12",
  "Boner Armor|12",
  "Beer Can Scale Mail|12",
  "Stegosaurus Plate Mail|12",
  "Food Chain Mail|13",
  "Splinter Mail|13",
  "Gelatinous Cube Jiggle-Vest|13",
  "Gorgosaurus Nugget Hide|13",
  "Touring Banded Mail|14",
  "Big Breast Plate|14",
  "Suburban Chainlink Mail|14",
  "Cast-Iron Skillet Plate|14",
  "Shelven Chain Mail|15",
  "Half and Half Plate|15",
  "Baron Vladimir Fartonnen Fat Suit|15",
  "99th Degree Stonecutter Apron|15",
  "Tectonic Plate Mail|16",
  "5 O'Clock Shadow Mail|16",
  "Diplodocus Ribcage Plate|16",
  "Nokia 3310 Interlocking Mail|16",
  "Masterwork Plate Mail|17",
  "ABS|17",
  "Lead Apron of Dental Defense|17",
  "Chocobo Feather Down Mail|17",
  "Kevlar|18",
  "Grandmaster Plate Mail|18",
  "Triceratops Bone Plate|18",
  "Tupperware Hermetic Plate|18",
  "Titan-anium|19",
  "Gorgonzola Plate|19",
  "Cheese Elemental Curd Plating|19",
  "Titanosaurus Bone Half Plate|20",
  "Brian Blessed Mail|20",
  "Mitrail Mail|21",
  "Grimdark Double-Hell Slayer Mail|21",
  "Sharknado Chitin Cuirass|21",
  "Proton Pack Lead Lining|22",
  "Sylvan Mail|22",
  "Doom 2 BFG Plate|23",
  "Brontosaurus Backbone Plate|23",
  "Manticore Spiked Half Plate|23",
  "Cyborg Putin Titanium Shell|24",
  "Bad Dragon Scale Mail|24",
  "Vibranium Half Plate|25",
  "Stupid Sexy Elf Silkweave|25",
  "Trogdor Burnished Plate|25",
  "Gannondork Evil Half Plate|26",
  "Diamond Mail|26",
  "Vibrabium Full Plate|27",
  "Orcus Dorcus Bone Mail|27",
  "Bed Baphomet and Beyond Terrycloth Plate|28",
  "Drow Half Plate|28",
  "Drow Full Plate|29",
  "Thirsty Cyberman Steel Chassis|29",
  "Elder Pinky and the Brain Dome|30",
  "Mithril Half Plate|30",
  "Adamantine Half Plate|31",
  "Arizona Tea Phoenix Featherplate|31",
  "Darth Mall Clearance Plate|32",
  "Mithril Full Plate|32",
  "Underdark Under Armor|33",
  "Asmodeus Fine-Ass Leathers|33",
  "Armor of Memnon|34",
  "Dr Doom PhD Monogrammed Cuirass|34",
  "Grand Admiral Thrawn Uniform Mail|35",
  "Breastplate of Herakles|35",
  "Adamantine Full Plate|36",
  "Darth Vader Respirator Plate|36",
  "Seattle Kraken Tentacle Weave|37",
  "Ablative Armor|37",
  "Beskar Armor|38",
  "Demogorgon Carapace Mail|38",
  "Tearassque Shell Plating|39",
  "Godzilla Scale|39",
  "Iron Man M42|40",
  "Tiamat Rainbow Scales|40",
  "Thanos Bedazzled Carapace|41",
  "Symbiote Suit|41",
  "Hulk Buster|42",
  "Cthulhu Eldritch Squiddies|42",
  "Strahd Dramatic-Cape Mail|43",
  "Use the Force Field|43",
  "Procrastination Guilt-Plate|44",
  "Spawn Necroplasm Shroud|44",
  "Gundam Ceramic Armor|45",
  "Guyver Bio-Booster Exosuit|45",
  "Plot Armor|46",
  "DM Screen of Damage Immunity|46",
  "Save-Scummed Invulnerability Shell|47",
  "Quantum Uncertainty Bodysuit|47",
  "Infinite Health Cheat Engine Mesh|48",
  "Deus Ex Machina Plate|48",
  "Dev-Console God-Mode Rig|49",
  "Immunity-to-Narrative-Consequences Mail|49",
  "Source Code Hex Armor|50",
  "Main Character Plot Armor of Destiny|50",
];

// from 39 to 231 Weapons
K.Weapons = [
  "Hollow log|0",
  "Self defense fruit|0",
  "Stinky cheese|0",
  "Wet Noodle|0",
  "Wet Pool Noodle|0",
  "Rolled-Up Newspaper|0",
  "Stale French Baguette|0",
  "Pointy Stick|1",
  "Rusty Butter Knife|1",
  "Slightly Sharpened Toothpick|1",
  "Tube Sock Full of Pennies|1",
  "Broken Bottle|1",
  "Knifes too short|1",
  "Oxgoad|1",
  "Shiv|1",
  "Ugly Stick|1",
  "Warhammer Figurine|1",
  "Eelspear|2",
  "Handpeen|2",
  "Hard Rock|2",
  "My So Called Knife|2",
  "Thyme Hammer|2",
  "Wheel of hard cheese|2",
  "Heavy Phonebook|2",
  "Limp Celery Stalk|2",
  "Plastic Spork of Doom|2",
  "Unsharpened No. 2 Pencil|2",
  "Cast-Iron Skillet|3",
  "Spatula of Searing|3",
  "Rusty Tire Iron|3",
  "Croquet Mallet|3",
  "Tactical Spork|3",
  "Axe Body Spray|3",
  "Blaseball Bat|3",
  "Colostomy bag|3",
  "David Bowie Knife|3",
  "Knight Club|3",
  "Sling|3",
  "Kinky Studded Paddle|3",
  "Battleadze|4",
  "Cloaken Dagger|4",
  "Crowbar|4",
  "Devo-whip|4",
  "Nun-chunks|4",
  "Pogo-stick|4",
  "Shuri Ken|4",
  "Three-Quarters Staff|4",
  "Flyswatter of Mild Agony|4",
  "Barstool of Cleaving|4",
  "Weed Whacker|4",
  "Golf Club of Despair|4",
  "Ball-Peen Hammer Time|5",
  "Meat Tenderizer|5",
  "Cricket Bat of Justice|5",
  "Fencing Foil Wrapped in Bacon|5",
  "Baselard|5",
  "Golf club|5",
  "Horsemans pick|5",
  "Leafmace|5",
  "Longish-iron|5",
  "Poachard|5",
  "Rock Lobster|5",
  "Shortish-sword|5",
  "Benjamin Bludgeon|6",
  "Crankbow|6",
  "Longish-sword|6",
  "Mack the Knife|6",
  "Mid-Morning Star|6",
  "Sling Blade|6",
  "Whinyard|6",
  "Windu Mace|6",
  "Morning Wood Star|6",
  "Halberd-ier Than Thou|6",
  "Glockenspiel|6",
  "Crossbow-tie|6",
  "Billhook Clinton|7",
  "Clay-More or Less|7",
  "Glaive-Digger|7",
  "Flail Fail|7",
  "Blibo|7",
  "Broadsword|7",
  "Chip n Flail|7",
  "Flogger|7",
  "Kreen|7",
  "Not-Nice Pick|7",
  "Tail Pike|7",
  "Warhammer|7",
  "Armand Hammer|8",
  "Capital Gains Axe|8",
  "Die Bardiche|8",
  "Katana|8",
  "Knife of Brian|8",
  "Pole-adze|8",
  "Sonic the Hedgehog Screwdriver|8",
  "Spontoon|8",
  "Scimitar-tar Sauce|8",
  "Battle-Axe Body Wash|8",
  "Partisan Politics Pike|8",
  "Zweihänder-job|8",
  "Stiletto-Heel Dagger|9",
  "Rapier Wit|9",
  "Nunchaku-Laden|9",
  "War Pick-Up Line|9",
  "Bastard Sword|9",
  "Ghoul-whip|9",
  "Knife Beater|9",
  "Peen-arm|9",
  "Pen Estoc|9",
  "Peregrine Falchion|9",
  "Wit Rapier|9",
  "Cloud Butters Sword|10",
  "Crossfit bow|10",
  "Culverin|10",
  "Inheritance Axe|10",
  "Lance-a-lot|10",
  "Tiger-tooth saber|10",
  "Yoda's stick|10",
  "Greatsword of Compensating|10",
  "Flametongue Depressor|10",
  "Vorpal Cheese Slicer|10",
  "Boomerang with Trust Issues|11",
  "Atlatl-Chat|11",
  "Trident of Bubbles|11",
  "Blunderbuss|11",
  "Dick Van Pike|11",
  "Hal's beard|11",
  "Icewind Flail|11",
  "White-tailed Spear|11",
  "Batarang|12",
  "Maxwells Silver Hammer|12",
  "Sword of Shan n Ara|12",
  "Sword of Tooth|12",
  "Trident Gun|12",
  "Holy Water Balloon Launcher|12",
  "Longbow of the Receding Hairline|12",
  "Glaive of the Grave Dancer|13",
  "Staff of Infinite Pointing|13",
  "Bandyclef|13",
  "Lasso of Sleuth|13",
  "Millenium Falchion|13",
  "My Saber Totoro|13",
  "Spear of Lou|13",
  "Chekhovs Gun|14",
  "Green Powder Ring|14",
  "Ham Cannon|14",
  "Steampunk Chainsaw|14",
  "Sword of Griff n Door|14",
  "Guillotine on a Stick|14",
  "Warscythe of Seasonal Allergies|14",
  "Buster Buster Sword|15",
  "Megaman Buster Cannon|15",
  "Bat-a-rang|15",
  "Glamdrink|15",
  "Ye Olde Shotgun|15",
  "Tron Disc|15",
  "Hoe of Destruction|16",
  "Lance of Longitude|16",
  "Lightsaber|16",
  "Goldeneye Klobb|16",
  "Cricket Noisy Blaster|16",
  "Scorpion's Kunai Rope|17",
  "Needler of Needle-Dicking|17",
  "Mjölnir|17",
  "Spear of Density|17",
  "Proton Pack|18",
  "Holy Hand Grenade of Antioch|18",
  "Crowbar of Gordon|18",
  "Doom Super Shotgun|18",
  "Energy Sword with Low Battery|19",
  "Soul Reaver of Souls|19",
  "Draggin Lance|19",
  "Chainsaw Hand|19",
  "Freddys Glove|20",
  "Gravity Gun|20",
  "Ash's Boomstick|20",
  "Blade of Olympus Mons|21",
  "Lancer Chainsaw Rifle|21",
  "Portal Kombat Gun|21",
  "Let it Keyblade|22",
  "Gunblade with No Recoil|22",
  "Masamune the Long Way|23",
  "Fat Albert Man|23",
  "Wabbajack-you-up|24",
  "Frostmourne-ing Routine|24",
  "Gungnir the Sharp|25",
  "Body Gravity Hammer|25",
  "Dagger of Thyme|26",
  "Spear of Longinus Longboy|26",
  "Sword of Casual Murder|27",
  "Busta Sword|27",
  "BFG Its-Over-9000|28",
  "Thanos Copter Blade|28",
  "Raygun Mk II|29",
  "Ivory and Ebony Blade|29",
  "He-Man Power Sword|30",
  "Thunderfury Blessed Blade of the Windseeker|30",
  "Death Star Pocket Laser|31",
  "Star Trek Phaser|31",
  "Sword of Omens|32",
  "Wave Motion Gun|33",
  "Golden Girls Gun|33",
  "Beam Katana|34",
  "Master Sword|35",
  "Omni-Wrench 8000|35",
  "Andúril|36",
  "X Callie Bur|37",
  "Buster Cannon Over 9000|37",
  "Hackmaster +12 Sword|38",
  "Muramasa|39",
  "Monado Blade of Spoilers|39",
  "Darksaber|40",
  "R.Y.N.O.|41",
  "Gurren Lagann Giga Drill|41",
  "Murasame|42",
  "Sword of Seven Hundred Cuts|42",
  "Ultima Blade|43",
  "Excalipoor But It Hits|43",
  "Infinity Gauntlet with Knockoff Stones|44",
  "Vorpal Railgun|44",
  "Some Anime Bullshit|45",
  "Yamato Spatial Katana|45",
  "The Ban Hammer|46",
  "Galactic Giga-Drill Breaker|46",
  "Nuke on a Stick|47",
  "Save-Scummer's Critical Dagger|47",
  "Death Star Key fob|48",
  "Reality-Deleting Glitch Wand|48",
  "Dev Console Kill-Command Stylus|49",
  "Infinite Loop God-Scythe|49",
  "The Source Code Eraser|50",
  "The One True Plot Device|50",
];

// from 37 to 91 Specials
K.Specials = [
  "Albatross",
  "Alembic",
  "Altar",
  "Amethyst",
  "Ankh",
  "Anklet",
  "Antidote",
  "Apparatus",
  "Arrow",
  "Bandolier",
  "Bell",
  "Bijou",
  "Bracelet",
  "Brassiere",
  "Spork",
  "Brazier",
  "Brocade",
  "Brooch",
  "Calcinator",
  "Candelabra",
  "Candle",
  "Cape",
  "Cauldron",
  "Charm",
  "Claw",
  "Cobble",
  "Coin",
  "Corset",
  "Crown",
  "Diadem",
  "Diary",
  "Elixir",
  "Fang",
  "Feather",
  "Fedora",
  "Festoon",
  "Figurine",
  "Fleece",
  "Galoon",
  "Gammel",
  "Garnet",
  "Gemstone",
  "Gimcrack",
  "Gimlet",
  "Globe",
  "Googles",
  "Grimoire",
  "Hood",
  "Hymnal",
  "Idol",
  "Ink pot",
  "Journal",
  "Lamp",
  "Laurel",
  "Lens",
  "Loom",
  "Mask",
  "Mortar",
  "Music box",
  "Necklace",
  "Nipple Ring",
  "Oil",
  "Orb",
  "Ornament",
  "Pestle",
  "Phial",
  "Philter",
  "Pixie-dust",
  "Pokédex",
  "Potion",
  "Pouch",
  "Quill",
  "Ring",
  "Robe",
  "Saddle",
  "Scabbard",
  "Sceptre",
  "Schwartz",
  "Scroll",
  "Shard",
  "Spangle",
  "Sphere",
  "Spork",
  "Statue",
  "Talisman",
  "Thong",
  "Tiara",
  "Token",
  "Tome",
  "Vulpeculum",
  "Wand",
  ];

// from 33 to 87 Item Attributes
K.ItemAttrib = [
  "Animated",
  "Arcane",
  "Artisinal",
  "Astral",
  "Austere",
  "Bedazzled",
  "Benevolent",
  "Blessed",
  "Chaosified",
  "Charming",
  "Color Coordinated",
  "Crafted",
  "Cromulent",
  "Cruciate",
  "Crystalline",
  "Cyber",
  "Deadly",
  "Diamond Encrusted",
  "Discombobulated",
  "Double-Shot",
  "Dual",
  "Eccentric",
  "Ectoplasmic",
  "Embiggened",
  "En Fuego",
  "Enchantified",
  "Ensorcelated",
  "Erotic",
  "Exotic",
  "Fearsome",
  "Festooned",
  "Filigreed",
  "Fine-Ass",
  "Flirting",
  "Foppish",
  "Frippery",
  "Frotzy",
  "Garlanded",
  "Gently-used",
  "Gilded",
  "Gleaming",
  "Gluten-free",
  "Golden",
  "Grandiose",
  "Holy Forkballs",
  "House Broken",
  "Invisible",
  "Iron",
  "Krystal",
  "Legendary",
  "Lucky",
  "Ludicrous",
  "Magicalastic",
  "Magnificent",
  "Maniacal",
  "Mecha",
  "Mithrallic",
  "Most Impressive",
  "Mythic",
  "Naked",
  "Officially Licensed",
  "One True",
  "Ormolu",
  "Ostentatious",
  "Pay-to-Win",
  "Pre-Owned",
  "Precious",
  "Proverbial",
  "Puissant",
  "Quirky",
  "Recently Sanitized",
  "Redonkulous",
  "Reverential",
  "Sacred",
  "Scrumtrulescent",
  "Shelven",
  "Shiny",
  "Spectral",
  "Talking",
  "Thematically Appropriate",
  "Travelocity-Gnome-Made",
  "Underdark",
  "Unearthly",
  "Unpredictable",
  "Venti",
  "Vorpal",
  "Wild",  ];

// from 52 to 178 Item Ofs
K.ItemOfs = [
  "Acrimony",
  "Adorkable",
  "Algorithm Optimization",
  "ASMR Whispering",
  "Assembly Required",
  "Awkward Silences",
  "Being Ratioed",
  "Binge Watching",
  "Bitcoin",
  "Boaty McBoatface",
  "Bullshot",
  "Buyer's Remorse",
  "Cancel Culture",
  "Cardio",
  "Catfishing",
  "Chaos Emerald",
  "Chillaxing",
  "Clickbait",
  "Comfort Inn",
  "Copypasta",
  "Cottagecore",
  "Crafting Minigames",
  "Cromulence",
  "Crypto Scams",
  "Dad Bod",
  "Danger Mouse",
  "Deepfakes",
  "Dental Work",
  "Diamonique",
  "Dice Jailing",
  "Dietary Restrictions",
  "Dignard",
  "Domination",
  "Doomscrolling",
  "Douchebaggery",
  "Dude-bros",
  "e-Barrassment",
  "Efficiency",
  "Electrum",
  "Embiggening",
  "Emotional Baggage",
  "Escort Missions",
  "Expired Milk",
  "Extroversion",
  "Fealty",
  "Fear Factor",
  "Fetch Quests",
  "FOMO",
  "Foreboding",
  "Foreshadowing",
  "Freemium",
  "Friendly Fire",
  "Fursuits",
  "Fusion Frenzy",
  "Gank Squads",
  "Gas Station Sushi",
  "Gaslighting",
  "Gatekeeping",
  "Ghosting",
  "Girlbossing",
  "Glamping",
  "Goblin Mode",
  "Google-Fu",
  "Grob",
  "Guile",
  "Hangry",
  "Happiness",
  "Hidden Fees",
  "Hulkamania",
  "Humble-Bragging",
  "Hunger Games",
  "Hurting",
  "Hydragyrum",
  "Imposter Syndrome",
  "Incarceration",
  "Infinite Buffering",
  "Influencers",
  "Infoganda",
  "Internment",
  "Intrusion",
  "Invisibility",
  "Invisible Walls",
  "Item Duplication",
  "Jeggings",
  "Joy Division",
  "Jury Duty",
  "Lag Spikes",
  "LARPing",
  "Live-Tweeeting",
  "Lolcats",
  "Looksmaxing",
  "Lootbox Gambling",
  "Loyalty",
  "Main Character Syndrome",
  "Manscaping",
  "Mansplaning",
  "Mermaidcore",
  "Metagaming",
  "Microdosing",
  "Middle Management",
  "Mild Inconvenience",
  "Min-Maxing",
  "Misapprehension",
  "Missed Connections",
  "Mogging",
  "Mom Jeans",
  "Murderhoboing",
  "Natural 1s",
  "Nervousness",
  "NFTs",
  "Nystul",
  "Overthinking",
  "Parallel Parking",
  "Parasocial Relationships",
  "Passive Aggression",
  "Patience",
  "Penis Envy",
  "Performative Cruelty",
  "Perspicacity",
  "Petulance",
  "Pits of Despair",
  "Pleasure",
  "Pole Dancing",
  "Practicality",
  "Prurience",
  "Psychosexual",
  "Punctuality",
  "Pungent Leftovers",
  "Quick-Time Events",
  "Quiet Desperation",
  "Quiet Luxury",
  "Rapidity",
  "Respec Regret",
  "Rizz",
  "Roblox",
  "rock-paper-scissors-lizard-Spock",
  "Rules Lawyering",
  "Save Scumming",
  "Sea Shanties",
  "Server Maintenance",
  "Shock and Awe",
  "Silent Quitting",
  "Situationship",
  "Skibidi",
  "Skill Trees",
  "Snowflakes",
  "Social Distancing",
  "Solitude",
  "Song of Silence",
  "Spam Calls",
  "Spamalot",
  "Spygate",
  "Stubbed Toes",
  "Subconscious Dread",
  "Submission",
  "Subtweet",
  "Suffering",
  "Tax Audits",
  "Text Offenders",
  "the Bone",
  "the Friend Zone",
  "TikTok",
  "Torpor",
  "Trauma Dumping",
  "Trolling",
  "Twerking",
  "Unboxing Videos",
  "Unskippable Cutscenes",
  "Unsolicited Opinions",
  "Unsubscribe Buttons",
  "Vecna",
  "Vibe Checks",
  "Web 3.0",
  "Wet Socks",
  "Wheel of Fortune",
  "Worry",
  "Yassification",
  "Zero Inbox",
];

// from 42 to 180 Boring Items
K.BoringItems = [
  "30 rocks",
  "acme anvil",
  "Amulet of Yendor",
  "animal cracker barrel",
  "Apeture Science cake",  
  "bag of lawn clippings",
  "bell, book and candle",
  "bent paperclip",
  "Bible belt buckle",
  "bird bath and beyond",
  "blaseball",
  "blubber gloves",
  "blue shell fragment",
  "bread bag twist tie",
  "broken Master Sword hilt",
  "broken zipper pull",
  "can of worms (opened)",
  "carrot prop",
  "casket case",
  "chaise lounge",
  "chamber pot",
  "chip on a shoulder",
  "chocobo dung pellet",
  "Cleveland femur",
  "clown shoe",
  "clump of wet dryer lint",
  "combed beef",
  "Companion Cube ash",
  "concrete canoe",
  "cookie crumbs",
  "counterpane",
  "cracked pipe",
  "cracked plastic comb",
  "credenza",
  "crowbar signed by Gordon Freeman",
  "crumpled newspaper",
  "crushed soda can full of cigarette butts",
  "crusty sock",
  "crusty sponge named Bob",
  "crusty toenail clipping",
  "dead AAA battery",
  "dead cat",
  "deep fake",
  "defective Pip-Boy screen",
  "deflated whoopee cushion",
  "dirt bag",
  "dirty asstray",
  "Doom floppy disk 3 of 5 (corrupt)",
  "drop in the bucket",
  "dry ballpoint pen",
  "dry-erase marker with no cap",
  "duck soup",
  "dust bunny",
  "ear wax candle",
  "empty estus flask",
  "empty meat wallet",
  "empty Pez dispenser",
  "expired Bed Bath & Beyond coupon",
  "exploding cigar box",
  "Face of Bo",
  "fish eyes",
  "fish hook up",
  "flattened penny from a zoo machine",
  "freemason jar",
  "frontyard milkshake",
  "g.e.c.k.",
  "get over writ",
  "glass onion",
  "gnawed chicken bone",
  "Golden Ring that does nothing",
  "grain of salt",
  "greasy brown paper bag",
  "hairball of unknown origin",
  "half-baked idea",
  "half-eaten Slim Jim",
  "half-melted birthday candle",
  "haystack in a needle",
  "hitchhiker towel",
  "hoedown",
  "I.O.U.",
  "inconvenient truth",
  "ink hair brush",
  "jar of pickled pigs' feet broth",
  "jeggings",
  "jiggies",
  "Jiminy Cricket Bat",
  "kinky restraints",
  "letter unopener",
  "lid to a Tupperware container that doesn't exist",
  "literal and figurative easter egg",
  "little blouse on the prairie",
  "lunchpail",
  "Mario coin",
  "metaphorical elephant in the room",
  "Mikes Semi-Hard Lemonade",
  "Minecraft dirt block",
  "moldy tea bag",
  "more cowbell",
  "Mr. Bucket",
  "mystery brass knob",
  "mystery jerky strip",
  "nine inch nail",
  "nonfungible token",
  "nosegay",
  "orange au jus",
  "oregon trail axle",
  "pandora box",
  "petrified french fry found under car seat",
  "piece of eden",
  "piece of eight",
  "pig in a poke",
  "pint of rice cream",
  "plague rat",
  "planter peanuts",
  "plastic Poké Ball with a rock inside",
  "plastic spork with a broken prong",
  "pocket full of lint",
  "Quaker instant goatmeal",
  "quantum particle of dust",
  "qunari artifact",
  "red herring bone",
  "RL Beer Stein",
  "robot chicken",
  "rolling pin-up",
  "rusty key that fits nothing",
  "scratched AOL 500 Hours CD-ROM",
  "septic plank",
  "shoot its a ladder",
  "shriveled grape that looks like a raisin",
  "shuttlecock and balls",
  "silver lining (detached)",
  "Sims green plumbob on a headband",
  "single fuzzy dice",
  "single novelty chopstick",
  "skull of mondain",
  "Skyrim iron dagger (mass-crafted)",
  "slippery slope sign",
  "smear window",
  "smoking gun without ammo",
  "soiled handkerchief",
  "solid snake cardboard box fragment",
  "Sonic shoe aglet",
  "spectacles",
  "spent Plasma Pistol battery",
  "spider monkey wrench",
  "spilled milk over which to cry",
  "splintered toothpick",
  "sponge glob",
  "stained ass window",
  "stained coaster from Applebee's",
  "stick of Fruit Stripes gum",
  "sticky coupon for 10% off oil change",
  "stinkwell",
  "stockpile of toilet paper",
  "stray Lego",
  "strip croquet mallet",
  "suspiciously warm cheese slice",
  "swouth pole",
  "take-out menu",
  "tamagotchi ghost",
  "tangled slinky",
  "teratoma",
  "Tetris L-block paperweight",
  "TF2 hat",
  "the poison for Kuzco",
  "the Twig Apple",
  "tickle pickles",
  "train of thought derailment",
  "triforce piece",
  "trinket",
  "tuppence",
  "unidentifiable charging cable",
  "unspooled cassette tape",
  "used bandage",
  "vault-tec jumpsuit thread",
  "vest in gate",
  "Vogon poem",
  "warm pocket mayonnaise packet",
  "water chip",
  "Wumpa fruit core",
];

// from 273 to 526 Monsters
K.Monsters = [
  "Ankle-biter|0|baby-teeth",
  "Charlotte the Spider|0|web",
  "Clingy Mothball|0|dust",
  "Cray-Crayfish|0|antenna",
  "Flik the Ant|0|antenna",
  "Frogger|0|leg",
  "Hollow Chocolate Bunny|0|ear",
  "Marty McFly|0|*",
  "Old Yeller|0|collar",
  "Pixelated Centipede|0|leg",
  "Ratatouille|0|tail",
  "Spores mold and fungus|0|infection",
  "Tick|0|spoon",
  "W.A.S.P.|0|church bulletin",
  "Cap'n Crunchberry|0|mouth cuts",
  "Dust Mite of Cthulhu|0|dander",
  "Sentient Toenail|0|clipping",
  "Passive-Aggressive Post-It|0|adhesive",
  "Spam Bot|1|captcha",
  "Cryptobro|1|seed phrase",
  "Mall Goth|1|eyeliner",
  "Bat-Mite|1|wing",
  "Berserker|1|shirt",
  "Billy Goat|1|beard",
  "Brownie the Elf|1|tusk",
  "Butt Pirate|1|booty",
  "Closet Skeleton|1|clavicle",
  "Club Scout|1|neckerchief",
  "Dervish|1|robe",
  "Garden Gnome|1|hat",
  "Goblin mode|1|ear",
  "Grid Bug|1|carapace",
  "Hobbled goblin|1|patella",
  "Kobold|1|penis",
  "Leprechaun in the Hood|1|wallet",
  "Little Mermaid|1|gills",
  "Manes|1|tooth",
  "Modest Mouse|1|tail",
  "Nebbish|1|belly",
  "Orc Zuckerberg|1|snout",
  "Ozzy Ostrich|1|beak",
  "Red Dwarf|1|drawers",
  "Rot Grub|1|eggsac",
  "Sea Elf|1|jerkin",
  "Sprite|1|can",
  "Stirge|1|proboscis",
  "Swamp Elf|1|lilypad",
  "The Merman|1|trident",
  "The Pixies|1|dust",
  "Trixy Nixie|1|webbing",
  "Yellow Mold|1|spore",
  "4chan Troglodyte|2|tail",
  "Bearded Lizard Man|2|tail",
  "Dryad|2|acorn",
  "Garden Octopus|2|beak",
  "Geico Caveman|2|club",
  "Ghoul Scout|2|cookie",
  "Ghoulfriend|2|muscle",
  "Grassy Gnoll|2|collar",
  "Green Slimer|2|sample",
  "Home Sweet Homunculus|2|fluid",
  "Koala-fied|2|heart",
  "More A Eel|2|sashimi",
  "Multicell|2|dendrite",
  "Nine Imp Nails|2|tail",
  "Pack of Camels|2|filter",
  "Porch Pirate of the Carribean|2|package",
  "Rob Zombie|2|forehead",
  "Stun Worm|2|trode",
  "Teen Wolf|2|paw",
  "Uruk-hai and dry|2|boot",
  "Whippet Good|2|collar",
  "Sex-Pest|2|harassment",
  "Vlogger|2|likes",
  "Sadboi|2|tears",
  "Spokesdog|2|commercial",
  "Gym Bro|2|shaker cup",
  "Roomba with a Butter Knife|2|scuff mark",
  "Unlicensed Muppet|2|cotton batting",
  "Podcast Host|2|patreon plug",
  "ASMR Whisperer|3|microphone saliva",
  "Drunk Uncle|3|unsolicited opinion",
  "Vape Cloud Elemental|3|cotton candy haze",
  "HOA Vice President|3|measuring tape",
  "e-girl|3|purple wig",
  "Teabagger|3|Mt Dew",
  "Bed-Bug-Bear|3|skin",
  "Boogie|3|slime",
  "Carrion Pub Crawler|3|egg",
  "Closet Quasit|3|tail",
  "Demure Lemure|3|blob",
  "Drag Sea Hag|3|wart",
  "Harpy Marx|3|mascara",
  "Hippie-griff|3|egg",
  "Hogbird|3|curl",
  "Iron Peasant Past & Future|3|chaff",
  "Jumpskin|3|shin",
  "Nymph Node|3|hanky",
  "Prince Triton|3|scale",
  "Secret of the Ooze|3|gravy",
  "Shadow the Hedgehog|3|silhouette",
  "Silkie|3|fur",
  "Snow Piercer|3|tip",
  "Stink-Bug-Boar|3|tusk",
  "Sylph Milf|3|thigh",
  "The Last Boy Scout|3|merit badge",
  "Violent Violet Fungi|3|spore",
  "Weaker Shrieker|3|stalk",
  "Woman-o-war|3|tentacle",
  "A Ghast aghast|4|vomit",
  "Centaur for Disease Control|4|rib",
  "Cooler Yeti|4|fur",
  "Corn Man|4|juice",
  "David the Gnome|4|hat",
  "Doppelganger|4|face",
  "Eagle Scout|4|merit badge",
  "Gargoyle|4|gravel",
  "Gelatinous Cube|4|jam",
  "Grape Ape|4|ass",
  "Hippocampus|4|mane",
  "Mini Giant|4|pompadour",
  "Mutant Babies|4|diaper",
  "Peryton on a Peloton|4|antler",
  "Poroid|4|node",
  "Purrmaid|4|hairball",
  "Stink Blink Dog|4|eyelid",
  "Tactics Ogre|4|talon",
  "Unicornio the Mexican unicorn|4|blood",
  "Wight Said Fred|4|lung",
  "Wolog|4|lemma",
  "Tumblrina|4|fan-fic",
  "Soy Latte Elemental|4|foam heart",
  "K-Pop Stan|4|photocard",
  "Lactose Intolerance Demon|4|rumble",
  "Goth IHOP Waitress|5|pancake syrup",
  "Midlife Crisis Centaur|5|convertible keys",
  "Binge-Watcher|5|crusty blanket",
  "Tweetstorm|5|RTs",
  "Twidiot|4|subtweets",
  "Broflake|4|tears",
  "Mansplainer|5|influencer",
  "Telefangelist|4|scam",
  "Twitterati|5|subtweets",
  "Bridezilla|5|entitlement",
  "Karen|5|complaint",
  "Bat out of Hell|5|meatloaf",
  "Beast with Two Axe|5|axe",
  "Bill Cosby|5|pudding pop",
  "Charizard|5|lawsuit",
  "Cockatrice|5|wattle",
  "Feral Muppet|5|fist",
  "Flail Bondsman|5|flail",
  "Gravy Elemental|5|stains",
  "Hell Hound|5|tongue",
  "Malebranche|5|fork",
  "Ogre Mage|5|apparel",
  "Owlbear|5|feather",
  "Rust Monster|5|shavings",
  "Savage Su-monster|5|tail",
  "Spider-Monkey|5|Mt. Dew",
  "Spitting Trouser Snake|5|infection",
  "Stun Bear|5|tooth",
  "Thirsty Satyr|5|hoof",
  "Windmills|5|*",
  "Wraith of God|5|finger",
  "Abominable Anhkheg|6|chitin",
  "Beefy Minotaur|6|map",
  "Butterscotch Custardbath|6|script",
  "Cantankerous Catoblepas|6|neck",
  "Embittered Erinyes|6|thong",
  "Grant Imahara's Sex Robot|6|dangly bits",
  "Iguanadon Nugget|6|thumb",
  "Leucrotta|6|hoof",
  "Manticore|6|spike",
  "Mork from Ork|6|egg",
  "Mummy Dearest|6|gauze",
  "Objectifying Medusa|6|eye",
  "Ochre Jelly|6|nucleus",
  "Playboy Bunny|6|ears",
  "Predditor|6|copypasta",
  "Sponge Rob Hair Pants|6|pants",
  "Succubus|6|bra",
  "Sweet Gnome Alabama|6|incest",
  "Twiiter Troll|6|hide",
  "Vampire Bat|6|wing",
  "White Stripes Dragon|6|tooth",
  "LinkedIn Thought Leader|6|buzzword",
  "Suburban Minotaur|6|cul-de-sac map",
  "Gas Station Sushi Roll|6|tapeworm",
  "Crossfit Evangelist|7|kettlebell",
  "Gluten Ghoul|7|sourdough starter",
  "Bearded Axe-Throwing Bartender|7|flannel scrap",
  "Djinn Djarin|7|lamp",
  "Drop Bear|7|punked",
  "Forlorn Xorn|7|jaw",
  "Forum Ban-shee|7|larynx",
  "In a Vest a Gator|7|tooth",
  "Interest devourer|7|brain",
  "Lame Duck Dodgers|7|bill",
  "Marilith|7|arm",
  "Mitzvah Bat|7|yarmulke",
  "Morkoth|7|teeth",
  "Orc Twain|7|book",
  "Otyugh|7|organ",
  "Pega-sus Impostor|7|aileron",
  "Peter Griffon|7|nest",
  "Rakshasa|7|pajamas",
  "Rodents of Unusual Size|7|tail",
  "Smelly Pirate Hookers|7|infection",
  "Spectre of the Past Participle|7|vestige",
  "Teddy Ruxpin|7|cassette",
  "Three and a half babies|7|diapers",
  "Balor Texas|8|whip",
  "Barbie Devil|8|flame",
  "Blumpkin-Spiced Latte|8|cup",
  "Ether Bunny|8|rag",
  "Fart Garfunkel Elemental|8|gas",
  "Gorgon Zolla|8|testicle",
  "Hail Hydra|8|gyrum",
  "Instant Rice Giant|8|grain",
  "Jagged Juggalos|8|make-up",
  "Jedi Mind Flayer Trick|8|tentacle",
  "Joan of Orc|8|cross",
  "Monoclonius Nugget|8|horn",
  "Mostly-Invisible Stalker|8|*",
  "Pandering Pandaren|8|fur",
  "Rin Tin Tin Dragon|8|*",
  "Silent Hill Giant|8|corpse",
  "Slo-Mo-akum|8|frenum",
  "Sparkly Vampire|8|glitter",
  "Umber Hulk|8|claw",
  "Vrock and roll|8|neck",
  "OnlyFans Simp|8|credit card debt",
  "Spirit Halloween Squatter|8|cheap mask",
  "Beanie Baby Hoarder|8|tag protector",
  "Dodge Charger with 28% APR|9|exhaust pipe",
  "Spicy Chicken Sandwich Craze|9|pickle slice",
  "Influencer Apology Video|9|crocodile tears",
  "Ace of Beige Dragon|9|*",
  "Ankylosaurus Nugget|9|tail",
  "Blue Screen of Death Dragon|9|*",
  "Boner Devil|9|hook",
  "Brass Monkey Dragon|9|pole",
  "Bronze Age Dragon|9|medal",
  "Chocobo|9|feather",
  "Couatl|9|wing",
  "Gone to Plaid Dragon|9|sporrin",
  "Hezrou|9|leg",
  "Howard the Duck Duck Goose|9|bill",
  "Iron Man Giant|9|sadness",
  "Jam and Jellyrock|9|seedling",
  "Mimic Mimic|9|hinge",
  "Naga|9|rattle",
  "Orc Ruffalo|9|script",
  "Porcelain Giant|9|fixture",
  "Rebecca Black Dragon|9|*",
  "Robot Unicorn|9|horn",
  "Rolling Stone Giant|9|hatchling",
  "Shedu|9|hoof",
  "Shitake Shrieker|9|fungi",
  "Wil-Wheaton-o'-the-Wisp|9|wisp",
  "4chan Lurker|10|sac",
  "Bacon Elemental|10|bit",
  "Black Sabbath Pudding|10|saliva",
  "Buffy Vampire|10|quips",
  "Darkwing Duck and Cover|10|bill",
  "Efreet Willy|10|cinder",
  "Glabrezu|10|collar",
  "Green Hornet Dragon|10|*",
  "Jack Frost Giant|10|snowman",
  "Lo and Beholder|10|eyestalk",
  "Moogle|10|fur",
  "Never Catch Me Copper Dragon|10|loafer",
  "Orc Hamill|10|script",
  "Patrick Swayze Ghost|10|*",
  "Pebble Beach Golf Sphinx|10|paw",
  "Quartz Giant|10|crystal",
  "Rainbow Brite Eyes|10|sprite",
  "Red Hot Chili Peppers Dragon|10|cocktail",
  "Shambling Mound|10|mulch",
  "Stay Gold Ponyboy Dragon|10|filling",
  "Threaten Ettin|10|fur",
  "Tree-ant-man and wasp|10|acorn",
  "Unskippable YouTube Ad|10|buffering ring",
  "NFT Ape|10|ugly jpeg",
  "IKEA Assembly Golem|10|allen wrench",
  "Air Fryer Zealot|11|crispy skin",
  "Dungeon Master's Girlfriend's Pet|11|plot armor",
  "A piñata full of fire bees|11|stinger",
  "Adventure Time Lord|11|screwdriver",
  "Beef Giant|11|steak",
  "Canadian 'Eh Holes|11|timbits",
  "Chimera Primavera|11|pasta",
  "Dread Gazebo|11|wood",
  "Flail Earnhardt|11|wreckage",
  "Jump Roper|11|twine",
  "Kindle Fire Giant|11|cigarettes",
  "King Triton|11|trident",
  "Lichie Lich|11|crown",
  "Nalfeshnee|11|tusk",
  "Neo-Otyugh|11|organ ",
  "Penis Guytrap|11|root",
  "Remorhaz|11|protrusion",
  "Sgt Poopers Lonely Farts Club Band|11|brown note",
  "Sharknado|11|fin",
  "Skeletor|11|bone",
  "Smallcox Outbreak|11|infection",
  "Vanilla Ice Devil|11|snow",
  "12-foot-tall skeleton|12|big bone",
  "A French Douchebaguette|12|crumbs",
  "Amazon Optimus Prime|12|cardboard",
  "Cloud Strife Giant|12|condensation",
  "Decidely Not Sexy Skeksis|12|beak",
  "Donkey Show-and-Tell|12|fur",
  "Feral snaggle-tooth crotch goblins|12|tooth",
  "Hairless ape with much anxiety|12|pills",
  "Hidden Valley Ranch-hand|12|bottle",
  "Humidity Giant|12|drops",
  "Jake from State Farm|12|khakis",
  "Je ne sais quoi|12|*",
  "Kentucky Fried Children|12|crispy bits",
  "Mastodon|12|tusk",
  "Megalosaurus Nugget|12|jaw",
  "Pentasaurus Nugget|12|head",
  "Porn Elemental|12|lube",
  "Silver Surfer Dragon|12|*",
  "Stubborn Adamantoise|12|shell",
  "Trapper Keeper|12|shag",
  "Pop-Punk Bassist|12|wallet chain",
  "Adult Disney Fanatic|12|mouse ears",
  "Buc-ee the Beaver|13|brisket grease",
  "Costco Sample Feeder|13|toothpick",
  "A 5th Grader smarter than you|13|book",
  "Cactuar|13|needle",
  "Chuck E Cheese Knife|13|cold dead eyes",
  "Cock Cockula|13|lips",
  "Conan O Brien the Bardbarian|13|hair",
  "Daddy Mothman|13|feather",
  "Dragon Teenage Mutant Ninja Turtle|13|shell",
  "Florida Man|13|gun",
  "Frank N Furter|13|fishnet",
  "Gorgosaurus Nugget|13|arm",
  "Hector the Love Nectar Injector|13|nectar",
  "Hulking Himbo|13|beefcake",
  "Lazarus Pit Fiend|13|seed",
  "Loki's horse baby|13|hooves",
  "Lord Adolphus Reginald Cockwomble Spunktrumpet the Third Esquire|13|ego",
  "Mr Planters|13|nuts",
  "Porg-stars|13|wing",
  "Teenage Mutant Ninja Squirtle|13|shell",
  "That sexy sexy Green M&M™|13|shell",
  "Why-vern?|13|question",
  "Albino howling shitgibbon|14|poo",
  "Baluchitherium|14|ear",
  "Baron Vladimir Fartonnen|14|fat",
  "Cardboard Golem|14|recycling",
  "Cheese Elemental|14|curd",
  "Gollum|14|precious",
  "Sherrif of Nottingham|14|taxes",
  "Ton-Tonberry|14|knife",
  "Tyrion Lannister|14|wine",
  "Wankpuffin Nobsocket Shitflute|14|flute",
  "Hot Tub Streamer|14|inflatable flamingo",
  "Self-Checkout Machine|14|unexpected item in bagging area",
  "Subreddit Mod on Power Trip|15|permaban notice",
  "Anacondas that love buns|15|buns",
  "Beer Golem|15|foam",
  "Elasmosaurus Nugget|15|neck",
  "Leather Golem|15|fob",
  "Malboro Light|15|vine",
  "Perfect Storm Giant|15|barometer",
  "Purple Worm|15|dung",
  "Salt N Pepperidge Farm|15|cookies",
  "Tinkerbell|15|attitude",
  "Trix Rabbit|15|cereal",
  "Chef Playboyardee|16|sauce",
  "Daffy Duck Confit|16|fat",
  "Hair Elemental|16|follicle",
  "Mongolian Death Worm|16|dung",
  "Nearly Headless Nick|16|head",
  "Rubber Golem|16|ball",
  "The Incredible Hulk Hogan|16|gamma radiation",
  "Triceratops Nugget|16|horn",
  "Turd Ferguson|16|hat",
  "Which-vern?|16|question",
  "Bigfoot Locker|17|blurry photo",
  "Caps Lock Ness Monster|17|tail",
  "Donald Duck Soup|17|broth",
  "Edward Rock-Paper-Scissorhands|17|scissors",
  "Jersey Devil|17|hockey jersey",
  "Jubilex|17|gel",
  "Oxygen Golem|17|platelet",
  "Schrödingers army of undead cats|17|quantum particle",
  "Skunk weed ape|17|hair",
  "What-vern?|17|question",
  "Stanley Cup Collector|16|straw topper",
  "Metaverse Avatar with No Legs|17|floating pelvis",
  "Animorph|18|paperback",
  "Batsquatch|18|talon",
  "Chupacabra|18|fang",
  "Corrosive Ooze|18|gunk",
  "Dwayne the Roc|18|wing",
  "Google Chromatic Dragon|18|scale",
  "Rolling in the Deep Stalker|18|saliva",
  "Stegosaurus Nugget|18|plate",
  "Tyrannosaurus Rex Nugget|18|forearm",
  "Where-vern?|18|question",
  "Trader Joe's Parking Lot Driver|18|dented bumper",
  "Cocaine Bear|19|powdered snout",
  "Astral Projection Stalker|19|silver cord",
  "Consentacle|19|slime",
  "Half-melted slushie|19|slime",
  "How-vern|19|question",
  "Mosh Pit Howler|19|shirt",
  "Phantom Hound of the Opera|19|mask",
  "Punk Rockworm Hydra|19|pincer",
  "Sasquatch|19|jerky",
  "Trogdor|19|peasant",
  "Tropic Thunderbird|19|feather",
  "Ahriman|20|spirit",
  "Barely Disguised Fetish Monster|20|whip",
  "House of Wax Phantom|20|dripping",
  "Peppa Pigfolk|20|bacon",
  "Tennessee Titan|20|sandal",
  "Spirit Airlines Flight Attendant|20|carry-on fee",
  "Lab-Grown Meat Meatball|21|petri dish",
  "Chairman of the Horde|21|private jet",
  "Grievous bodily harmicist|21|prescription",
  "Humphry Boggart|21|hat",
  "Undead Dragon Ball Z|21|dragonball",
  "Vorpal Bunny|21|teeth",
  "Cool Whip Scorpion|22|tub",
  "Cyborg Putin|22|rubles",
  "Demon Lord of the Flies|22|conch",
  "Dire Straits Wolf|22|video",
  "Hunger Games Daedra|22|whistle",
  "Cyberpunk Glitch Fiend|22|t-pose",
  "Glamping Instagrammer|23|fairy lights",
  "Behe-mothman|23|horn",
  "Dirty Laundry Golem|23|sock",
  "Dodge or Ram|23|horns",
  "Double Platinum Dragon|23|*",
  "Judge Dread Pirate Roberts|23|mask",
  "Ticketmaster Dynamic Pricing Golem|24|convenience fee",
  "Billionaire Submersible Pilot|25|logitech controller",
  "Diplodocus Nugget|24|fin",
  "Doomguard II BFG Edition|24|shotgun",
  "Lightning McQueen Elemental|24|kachow",
  "Manticore i9 Processor|24|thermal paste",
  "Shadow the Hedgehog Elemental|24|gun",
  "Ender Game Dragon|25|end portal",
  "Titanosaurus Nugget|25|fossil",
  "Void Tower of Terror|25|ash",
  "Which-Why-Were-Bear|25|paw",
  "Yeenoghu|25|flail",
  "Gelatinous Boob|26|jiggle",
  "One Winged Angel|26|feather",
  "Senior Vice President|26|business card",
  "Cadaver Collector Gadget|27|cadaver",
  "Health Inspector|27|citation",
  "Orcus Dorcus|27|wand",
  "Duolingo Owl|27|threat",
  "OpenAI Server Crash|28|red error code",
  "Brontosaurus Nugget|28|brain",
  "He Who Must Not Be Deadnamed|28|name",
  "High-brow Drow Inquisitor|28|eyebrow",
  "Dispater|29|matches",
  "Elder Pinky and the Brain|29|braincell",
  "Zombie Dragula|29|fangs",
  "Geryon|30|cornucopia",
  "Green Day Abishai|30|album",
  "Mother-in-Law|30|expectations",
  "Elon's Cybertruck|30|shattered armor glass",
  "Gannondork|31|triforce",
  "Skittering Treehouse of Horror|31|episode",
  "Asteroid Spider-Man|32|webbing",
  "More-goth|32|horn",
  "Ancient Deep Throat Crow|33|spit",
  "Darth Shopping Mall|33|half-off coupon",
  "Prime Hydration Drinker|33|plastic bottle",
  "Arizona Tea Phoenix|34|can",
  "Dr Doom PhD|34|mask",
  "Darkseid|35|mother box",
  "Steel Sexual Predator|35|sexts",
  "Ashen Knight Rider|36|tires",
  "The Betty White Witch|36|dentures",
  "Licked Lichen Lich|37|saliva",
  "Wicked Witch of the Upper NW|37|broom",
  "Zuckerberg in the Octagon|37|sunscreen sheen",
  "Lord Farquaad|38|martini",
  "The Lord of Beyblades|38|nostalgia",
  "Captain Barbossa|39|apple",
  "Cosmic Rocky Horror|39|fishnet",
  "Mal if a cent|40|staff",
  "Peach Pit Fiend|40|pit",
  "The Dark One|41|darkness",
  "Prostetnic Vogon Jeltz|42|poetry",
  "Baalzebul|43|pants",
  "Taylor Swift Private Jet|43|carbon emissions",
  "Hannibal Lecter|44|fava beans",
  "Grand Admiral Thrawn|45|art",
  "Low-key Loki|46|infinity stone",
  "Darth Vader|47|helmet",
  "Sauron|48|eye",
  "Imposter from Among Us|48|sus vent",
  "Kung Fu Chaos|49|insanity",
  "Mind Flayer Lich Itchybitch|50|tentacle",
  "Elder Tempest in a Teapot|51|ceramic chip",
  "Seattle Kraken|52|tentacle",
  "Bed Baphomet and Beyond|53|towel",
  "Jeff Bezos Prime Giant|53|same-day delivery",
  "Orcus Porkus Dorcus|54|bacon",
  "Thanos|55|gauntlet",
  "Cthulu|56|tentacle",
  "Asmodeus|57|leathers",
  "Demogorgon|58|tentacle",
  "Vecna|59|head",
  "Strahd|60|dramatic-cape",
  "The IRS Audit Inspector|60|w-2 form",
  "Tearassque|61|fart",
  "Tiamat|62|scale",
  "Greatwyrm|63|scale",
  "Gabe Newell Summer Sale|63|discount badge",
  "Death|64|cloak",
  "Procrastination|65|guilt",
  "Feature Creep|66|roadmap update",
];

// from 16 to 101 Monster Modifiers - Weren't implemented previously
K.MonMods = [
  "-5 Decomposed *",
  "-5 Brain-Dead *",
  "-5 Comatose *",
  "-5 Deflated *",
  "-4 Legless *",
  "-4 Extremely Hungover *",
  "-4 Narcoleptic *",
  "-4 Concussed *",
  "-4 Anemic *",
  "-4 Fœtal *",
  "-4 Dying *",
  "-4 Mortally Wounded *",
  "-3 Crippled *",
  "-3 Idiotic *",
  "-3 Infantile *",
  "-3 Depressed *",
  "-3 Blind As A Bat *",
  "-3 Wheezing *",
  "-3 Senile *",
  "-3 Inebriated *",
  "-3 Asthmatic *",
  "-3 Hypochondriac *",
  "-2 Sleep-Deprived *",
  "-2 Uncoordinated *",
  "-2 Constipated *",
  "-2 Distracted *",
  "-2 Mildewed *",
  "-2 Decidedly Sluggish *",
  "-2 Sunburned *",
  "-2 * with Knee Problems",
  "-2 Adolescent *",
  "-2 Very Sick *",
  "-2 Fairly Stupid *",
  "-1 Lesser *",
  "-1 Undernourished *",
  "-1 Not-So-Bright *",
  "-1 Sub-Par *",
  "-1 Slightly Dazed *",
  "-1 Budget *",
  "-1 Discount *",
  "-1 Store-Brand *",
  "-1 Mildly Confused *",
  "-1 Half-Hearted *",
  "-1 Low-Calorie *",
  "-1 Decaf *",
  "-1 Pigeon-Toed *",
  "+1 Greater *",
  "+1 Caffinated *",
  "+1 Annoyed *",
  "+1 Sugar-Rushed *",
  "+1 Passive-Aggressive *",
  "+1 Pre-Heated *",
  "+1 * with a Vengeance",
  "+1 Aggressively Moist *",
  "+1 Well-Rested *",
  "+1 Slightly Angry *",
  "+1 High-Fructose *",
  "+1 * Elder",
  "+2 Sonic *",
  "+2 War *",
  "+2 Battle-*",
  "+2 Tactical *",
  "+2 Armored *",
  "+2 Turbo *",
  "+2 Rabid *",
  "+2 * with Nunchucks",
  "+2 Ripped *",
  "+2 Enraged *",
  "+2 High-Octane *",
  "+2 Cyber-*",
  "+3 Were-*",
  "+3 Super-Sonic-*",
  "+3 Undead *",
  "+3 Nuclear *",
  "+3 Dread *",
  "+3 Berserk *",
  "+3 Ghostly *",
  "+3 Toxic *",
  "+3 Mutant *",
  "+3 * of Doom",
  "+3 Laser-Guided *",
  "+3 Badass *",
  "+4 Giant *",
  "+4 Mecha *",
  "+4 * Rex",
  "+4 Colossal *",
  "+4 Apocalyptic *",
  "+4 Hyper-*",
  "+4 * Prime",
  "+4 Doom-Forged *",
  "+4 Titanic *",
  "+4 Giga-*",
  "+4 Eldritch *",
  "+5 Kaiju *",
  "+5 Ultra-Instinct *",
  "+5 Planet-Buster *",
  "+5 Cosmic *",
  "+5 * 2.0",
  "+5 God-Tier *",
  "+6 Raid Boss *",
  "+6 Game-Breaking *"
];

// from 9 to 95 Offense Bad
K.OffenseBad = [
  "Tarnished|-1",
  "Cumbersome|-1",
  "Crooked|-1",
  "Weakened|-1",
  "Flimsy|-1",
  "Smudged|-1",
  "Blunt-ish|-1",
  "Sticky-Handled|-1",
  "Lukewarm|-1",
  "Chipped|-1",
  "Slightly-Wobbly|-1",
  "Unsharpened|-1",
  "Dusty|-1",
  "Splintery|-1",
  "Off-Balance|-1",
  "Greasy|-2",
  "Not-So-Sharp|-2",
  "Butter-Knife-Grade|-2",
  "Loose-Fitted|-2",
  "Tetanus-Prone|-2",
  "Mildewed|-2",
  "Awkward|-2",
  "Slippery|-2",
  "Clunky|-2",
  "Blunted|-2",
  "Dull|-2",
  "Icky|-2",
  "Unbalanced|-2",
  "Yielding|-2",
  "Rusty|-2",
  "Store-Brand|-3",
  "Feeble|-3",
  "Diminutive|-3",
  "Bent|-3",
  "Flaccid|-3",
  "Clearance-Rack|-3",
  "Counterfeit|-3",
  "Duct-Taped|-3",
  "Pewter|-3",
  "Cardboard-Core|-3",
  "Temu-Quality|-3",
  "Brittle|-3",
  "Shoddy|-3",
  "Fumbling|-3",
  "Snaggle-Toothed|-3",
  "Toothpick-Grade|-4",
  "Foam-Tipped|-4",
  "Styrofoam|-4",
  "Wobbly-Shafted|-4",
  "Soggy|-4",
  "Limp|-4",
  "Gag-Gift|-4",
  "Balsa-Wood|-4",
  "Shattered|-4",
  "Pudding-Soft|-4",
  "Padded|-4",
  "Unsubstantial|-4",
  "Lousy|-4",
  "Puny|-4",
  "Rotten|-5",
  "Rubber|-5",
  "Fragile|-5",
  "Woeful|-5",
  "Crumbled|-5",
  "Papier-Mâché|-5",
  "Moldy|-5",
  "Gelatinous|-5",
  "Comically-Soft|-5",
  "Inflatable|-5",
  "Spaghetti-Spined|-5",
  "Mildew-Ridden|-5",
  "Festering|-5",
  "Self-Denting|-6",
  "Abysmal|-6",
  "Disintegrating|-6",
  "Pathological|-6",
  "Catastrophic|-6",
  "Repulsive|-6",
  "Hazardous-to-User|-6",
  "Garbage-Tier|-6",
  "Decrepid|-6",
  "Worthless|-6",
  "Decayed|-6",
  "Odious|-6",
  "Horrendous|-7",
  "Nerf|-7",
  "Rancid|-7",
  "Cursed|-7",
  "Reverse-Vorpal|-7",
  "Emotionally-Defeated|-7",
  "Actively-Healing-the-Enemy|-7",
  "Existentially-Dreadful|-7",
  "DM-Spite-Infused|-8",
  "Anti-Sharp|-8",
  "Weaponized-Disappointment|-8"
];

// from 14 to 93 Defense Bad
K.DefenseBad = [
  "Holey|-1",
  "Patched|-1",
  "Faded|-1",
  "Weakened|-1",
  "Flimsy|-1",
  "Scratched|-1",
  "Loose-Stitched|-1",
  "Ill-Fitting|-1",
  "Stained|-1",
  "Unraveled|-1",
  "Creased|-1",
  "Slightly-Porous|-1",
  "Drafty|-1",
  "Pilled|-1",
  "Chafing|-1",
  "Sweat-Soaked|-2",
  "Termite-Nibbled|-2",
  "Duct-Taped|-2",
  "Splintered|-2",
  "Sagging|-2",
  "Dry-Rotted|-2",
  "Squeaky|-2",
  "Stinky|-2",
  "Stiff|-2",
  "Singed|-2",
  "Threadbare|-2",
  "Mildewed|-2",
  "Yielding|-2",
  "Rusty|-2",
  "Flawed|-2",
  "Moth-eaten|-3",
  "Torn|-3",
  "Dented|-3",
  "Warped|-3",
  "Corroded|-3",
  "Cardboard-Backed|-3",
  "See-Through|-3",
  "Burlap-Lined|-3",
  "Temu-Stitched|-3",
  "Bitten|-3",
  "Perforated|-3",
  "Shedding|-3",
  "Paper-Thin|-3",
  "Unraveling|-3",
  "Gape-Holed|-3",
  "Styrofoam|-4",
  "Tissue-Paper|-4",
  "Foil-Wrapped|-4",
  "Soggy|-4",
  "Brittle|-4",
  "Window-Screen|-4",
  "Edible|-4",
  "Crumbly|-4",
  "Cling-Wrapped|-4",
  "Mesh|-4",
  "Plastic|-4",
  "Cracked|-4",
  "Unsubstantial|-4",
  "Lousy|-4", 
  "Rotten|-5",
  "Pregnable|-5",
  "Exposed|-5",
  "Woeful|-5",
  "Disintegrating|-5",
  "Punctured|-5",
  "Shattered|-5",
  "Invertebrate|-5",
  "Deflated|-5",
  "Mold-Crusted|-5",
  "Termite-Hollowed|-5",
  "Festering|-5",
  "Self-Destructing|-6",
  "Non-Existent|-6",
  "Magnetized-to-Blades|-6",
  "Embarrassingly-Sheer|-6",
  "Crushed|-6",
  "Catastrophic|-6",
  "Decrepid|-6",
  "Worthless|-6",
  "Decayed|-6",
  "Odious|-6",
  "Open-Air|-6",
  "Horrendous|-7",
  "Naked|-7",
  "Rancid|-7",
  "Cursed|-7",
  "Critically-Compromised|-7",
  "Inverse-Armored|-7",
  "Bullseye-Painted|-7",
  "Stab-Attracting|-7",
  "Damage-Amplifying|-8",
  "Nudist-Grade|-8",
  "Existentially-Defenseless|-8",
];

// from 21 to 24 Races
K.Races = [
  "4chan Troll|CHA,INT",
  "Aware-Wolf|WIS,STR",
  "Demi-Canadian|WIS,DEX",
  "Double-Wookiee|CON,CHA",
  "Double-sided Bad Dragon|STR,MP Max",
  "Enchanted Talking Chamberpot|DEX,CHA",
  "Erotic Sonic Fan-Fic Abomination|HP Max,MP Max",
  "Filthy Stinkin Lich|MP Max,CON",
  "Goblin-Mode Satyr|MP Max,DEX",
  "High Treant|CON,STR",
  "Hungry Hungry Hobbit|DEX,CON",
  "I No Longer Care Bear|INT,WIS",
  "Miniature Giant Space Hamster|DEX,HP Max",
  "My Little Pygmy|CHA,WIS",
  "Nympho Nymph|CON,WIS",
  "Odorous Oompa Loompa|HP Max,INT",
  "Only Somewhat Racist Dwarf|HP Max,CON",
  "Pixie Ironically with a Pixie-Cut|MP Max,INT",
  "Poultrygeist|INT,DEX",
  "Reverse-Centaur|STR,CHA",
  "Sharkasaurus|STR,HP Max",
  "Stupid Sexy Elf|CHA,MP Max",
  "Thirsty Cyberman|INT,STR",
  "Travelocity Gnome|WIS,HP Max",];

// from 18 to 24 Klasses
K.Klasses = [
  "99th Degree Stonecutter|CON,STR",
  "Barbarian Pretzel|HP Max,CON",
  "Big Bad Voodoo Daddy|CHA,HP Max",
  "Blood-Sucking Lunatic|CHA,MP Max",  
  "Boston Cream Strangler|INT,HP Max",
  "Drug Healer|WIS,INT",
  "Drunken Forest Friar|STR,WIS",
  "Electric Monk|MP Max,INT",
  "Erotical Illusionist|INT,CHA",
  "Fatal Flatulist|INT,CON",
  "Grimdark Double-Hell Slayer|CON,DEX",
  "Hamburglar|DEX,CHA",
  "Internal Combustion Felon|STR,HP Max",
  "Paperback Fighter|STR,INT",
  "Paula Deen Paladin|WIS,CON",
  "Pinball Wizard|MP Max,DEX",
  "Sailor Rune|DEX,STR",
  "Shovel Knight|HP Max,DEX",
  "Sorcerer Supreme Pizza|WIS,MP Max",
  "Stranger Ranger|DEX,WIS",
  "Stubborn Jackass|HP Max,MP Max",
  "Super Show-off Saiyan|MP Max,STR",
  "Thief Executive Officer|CON,CHA",
  "United States Coast Bard|CHA,WIS",];

// from 9 to 76 Titles
K.Titles = [
  "Miss Ter",
  "Miss Uss",
  "Mister Mister",
  "Butterfly Madame",
  "Assistant Master",
  "Its-a-me",
  "Peastant 3rd Class",
  "Public Private",
  "Punishmnent Cpl.",
  "Slaughter Sgt.",
  "O Captain My Captain",
  "Kangaroo Captain",
  "Channel Serf",
  "Knave Intern",
  "Squire S. Quire",
  "Fright Knight",
  "A Hard Days Knight",
  "Last Friday Knight",
  "Three Dog Knight",
  "Date Knight",
  "Shovel Knight",
  "O Holy Knight",
  "Silent Knight",
  "Prom Knight",
  "Little Mister",
  "Miss Demeanor",
  "Miss Match",
  "Miss Guided",
  "Sir Charge",
  "Sir Render",
  "Sir Real",
  "Sir Loin",
  "Sir Cumfrance",
  "Madame Ovary",
  "Master of None",
  "Stonecutter",
  "Serf n' Turf",
  "Unpaid Intern",
  "Assistant to the Squire",
  "Squire for Hire",
  "Peasant Emeritus",
  "Junior Scullery Boy",
  "Temp Worker 1st Class",
  "Stable Sweeper",
  "Court Lackey",
  "Part-Time Errand Boy",
  "Private Property",
  "Private Parts",
  "Corporal Tunnel",
  "Lance Corporal Punishment",
  "Drill Sergeant at Arms",
  "Sergeant at Odds",
  "Acting Ensign",
  "Midshipman-in-Training",
  "Dishonorable Dischargee",
  "Bunk Inspector",
  "Boogie Knight",
  "One Night Stand Knight",
  "Arabian Knight",
  "Knighty-Night",
  "Knight Shift",
  "Saturday Knight Live",
  "Dark Knight Rises Late",
  "Opening Knight",
  "Knight Cap",
  "Knight Fever",
  "Friar Tuck-in",
  "Cleric with Bad Posture",
  "Pew Warmer",
  "Altar Boy Scout",
  "Village Idjut",
  "Town Crier of Tears",
  "Court Jester Reject",
  "Freelance Knave",
  "Yeoman of the Laundry Yard",
  "Deputy Dog-Catcher",
];

// from 14 to 123 Impressive Titles
K.ImpressiveTitles = [
  "Mayor McCheese",
  "Ozone Mayor",
  "Windows Media Mayor",
  "Flavortown Mayor",
  "Rear Admiral",
  "Admiral Rights Activist",
  "Great-ish Arch-Viscount",
  "Verified Influencer",
  "Reddit Moderator",
  "Sofa King",
  "Too Much of a Good King",
  "Do the Right King",
  "I Dont Want to Miss a King",
  "Sweetest King",
  "Burger King",
  "Keep your hands Queen",
  "Blue Queen of Death",
  "Scream Queen",
  "MiLord",
  "Lord of Directors",
  "MiLady",
  "The Real Slim Lady",
  "Nineteen Lady-Four",
  "Hasta La Vista Lady",
  "Hush Little Lady",
  "Ice Ice Lady",
  "Step-Prince Thrice-Removed",
  "Step-Princess Thrice-Removed",
  "Corned Chief",
  "Master Chef Chief",
  "Miss Chief",
  "Big Boss",
  "Mini Boss",
  "Pandoras Boss",
  "St. Louis Archbishop",
  "Left-to-Chancellor",
  "Marky-Marquis",
  "Dry and Baron",
  "Red Baron",
  "Red Baroness",
  "Nukem Duke",
  "I Kissed an Earl",
  "Grey Earl",
  "Juan Don",
  "Red Don",
  "Tsar of Trek",
  "Tsar of Wars",
  "Uncle Tom's Captain",
  "Pachelbel's Captain",
  "Modern Major-General",
  "Oh Lordy",
  "Rump Inspector General",
  "MVPVIPOMGWTFBBQ",
  "Commander in Briefs",
  "Ghost of Christmas President",
  "Email Abbess",
  "Bad Abbott",
  "Major Inquest General",
  "King of the Hill",
  "Smooooth Ope-Rater King",
  "Lion King",
  "Dairy Queen of Hearts",
  "Drama Queen of the Damned",
  "RuPaul's Drag Queen",
  "Return of the King",
  "Queen Size Mattress",
  "Lord of the Dance Dance Revolution",
  "Lord of the Flies with Honey",
  "Lord of the Ringside Seats",
  "Single Lady (All The)",
  "Lady Marmalade",
  "First Lady of Cringe",
  "Iron Duke of Hazzard",
  "Daisy Duke",
  "Duke of URL",
  "Earl Grey Tea Party",
  "Early to Bed Earl",
  "Baron von Trapp Family",
  "Robber Baron",
  "Baron Waste-Land",
  "Count Chocula",
  "Sesame Street Count",
  "No Count",
  "Viscountess Dracula",
  "Grand Duke of Hazard Pay",
  "Crown Prince of Bel-Air",
  "Fresh Prince of Thieves",
  "Princess and the Pea-Brain",
  "Captain Crunch",
  "Captain Obvious",
  "O-Captain-Where-Art-Thou",
  "General Tso",
  "General Malaise",
  "General Admission",
  "Brigadier General Store",
  "Corporal Punishment",
  "Sergeant at Harms",
  "Sergeant Pepperoni",
  "Major Disappointment",
  "Major League Bowler",
  "Private Eye-Roll",
  "Admiral Ackbarista",
  "Sub-Commander in Briefs",
  "Nightmare Mayor",
  "Grimace's Deputy Mayor",
  "Vice Prime Minister of Petty Grievances",
  "Assistant to the Regional Manager",
  "Chief Executive Ostrich",
  "Chief Vibes Officer",
  "Middle Management Overlord",
  "Bishop of Boffo",
  "Pope on a Rope",
  "Grand Inquisitive Inquisitor",
  "Notary Public Enemy #1",
  "Ambassador of Good Intentions",
  "Discord Admin Emeritus",
  "Certified Podcaster",
  "TikTok Archon",
  "Patreon Baron",
  "Subreddit Tyrant",
  "LinkedIn Thought Emperor",
  "Blue-Check Aristocrat",
  "Twitch Affiliated Warlord",
];